// 자동 생성 파일 — 직접 고치지 말 것. `npm run check` 가 다시 만든다.
// 홈 화면이 큰 콘텐츠 청크를 기다리지 않고 목차를 그리기 위한 메타데이터.

export const MANIFEST = [
  { id: "be-aff", sectionId: "tense", kind: "basic", title: "be동사 긍정", short: "긍정", group: "be동사", count: 10 },
  { id: "be-neg", sectionId: "tense", kind: "basic", title: "be동사 부정", short: "부정", group: "be동사", count: 8 },
  { id: "be-q", sectionId: "tense", kind: "basic", title: "be동사 의문", short: "의문", group: "be동사", count: 7 },
  { id: "be-negq", sectionId: "tense", kind: "basic", title: "be동사 부정의문", short: "부정의문", group: "be동사", count: 6 },
  { id: "be-review", sectionId: "tense", kind: "review", title: "be동사 통합 정리", short: "통합정리", group: "be동사", count: 11 },
  { id: "do-aff", sectionId: "tense", kind: "basic", title: "일반동사 긍정", short: "긍정", group: "일반동사", count: 8 },
  { id: "do-neg", sectionId: "tense", kind: "basic", title: "일반동사 부정", short: "부정", group: "일반동사", count: 6 },
  { id: "do-q", sectionId: "tense", kind: "basic", title: "일반동사 의문", short: "의문", group: "일반동사", count: 6 },
  { id: "do-negq", sectionId: "tense", kind: "basic", title: "일반동사 부정의문", short: "부정의문", group: "일반동사", count: 6 },
  { id: "do-review", sectionId: "tense", kind: "review", title: "일반동사 통합 정리", short: "통합정리", group: "일반동사", count: 11 },
  { id: "present-mega", sectionId: "tense", kind: "mega", title: "현재시제 대왕 정리", short: "현재시제 총정리", group: null, count: 12 },
  { id: "be-past", sectionId: "tense", kind: "basic", title: "be동사 과거", short: "be동사", group: "과거", count: 6 },
  { id: "do-past", sectionId: "tense", kind: "basic", title: "일반동사 과거", short: "일반동사", group: "과거", count: 7 },
  { id: "past-review", sectionId: "tense", kind: "review", title: "과거시제 정리", short: "정리", group: "과거", count: 10 },
  { id: "be-future", sectionId: "tense", kind: "basic", title: "be동사 미래", short: "be동사", group: "미래", count: 5 },
  { id: "do-future", sectionId: "tense", kind: "basic", title: "일반동사 미래", short: "일반동사", group: "미래", count: 6 },
  { id: "future-review", sectionId: "tense", kind: "review", title: "미래시제 정리", short: "정리", group: "미래", count: 10 },
  { id: "all-mega", sectionId: "tense", kind: "mega", title: "현재·과거·미래 대왕 정리", short: "전체 총정리", group: null, count: 12 },
  { id: "passive-basic", sectionId: "passive", kind: "basic", title: "수동태 기본", short: "기본", group: null, count: 8 },
  { id: "passive-negq", sectionId: "passive", kind: "basic", title: "수동태 부정·의문", short: "부정·의문", group: null, count: 6 },
  { id: "passive-45", sectionId: "passive", kind: "basic", title: "4·5형식 수동태", short: "4·5형식", group: null, count: 7 },
  { id: "passive-advanced", sectionId: "passive", kind: "basic", title: "심화 수동태 — 시제·조동사·동사구·by 이외 전치사", short: "심화", group: null, count: 7 },
  { id: "passive-review", sectionId: "passive", kind: "review", title: "수동태 통합 정리", short: "통합정리", group: null, count: 11 },
  { id: "noun", sectionId: "parts", kind: "basic", title: "명사 — 셀 수 있는/없는", short: "명사", group: null, count: 8 },
  { id: "adjective", sectionId: "parts", kind: "basic", title: "형용사 — 명사를 꾸민다", short: "형용사", group: null, count: 8 },
  { id: "adverb", sectionId: "parts", kind: "basic", title: "부사 — 동사를 꾸민다", short: "부사", group: null, count: 8 },
  { id: "parts-review", sectionId: "parts", kind: "review", title: "품사 통합 정리", short: "통합정리", group: null, count: 11 },
  { id: "conjunction", sectionId: "connect", kind: "basic", title: "접속사 — 단어·문장을 잇다", short: "접속사", group: null, count: 8 },
  { id: "preposition", sectionId: "connect", kind: "basic", title: "전치사 — 시간·장소를 표시", short: "전치사", group: null, count: 9 },
  { id: "modal", sectionId: "connect", kind: "basic", title: "조동사 — 동사에 의미를 더한다", short: "기본", group: "조동사", count: 8 },
  { id: "modal-have-pp", sectionId: "connect", kind: "basic", title: "조동사 + have + p.p — 과거에 대한 추측·후회", short: "have+p.p", group: "조동사", count: 7 },
  { id: "modal-idioms", sectionId: "connect", kind: "basic", title: "조동사 관용 — have to · ought to · used to 등", short: "관용", group: "조동사", count: 7 },
  { id: "adverb-clause", sectionId: "connect", kind: "basic", title: "부사절 접속사 심화 — 양보·조건·목적·시간", short: "부사절 접속사", group: null, count: 7 },
  { id: "connect-review", sectionId: "connect", kind: "review", title: "접속사·전치사·조동사 통합 정리", short: "통합정리", group: null, count: 12 },
  { id: "structure-1", sectionId: "structure", kind: "basic", title: "1형식 — 주어 + 동사", short: "1형식", group: null, count: 7 },
  { id: "structure-2", sectionId: "structure", kind: "basic", title: "2형식 — 주어 + 동사 + 보어", short: "2형식", group: null, count: 7 },
  { id: "structure-3", sectionId: "structure", kind: "basic", title: "3형식 — 주어 + 동사 + 목적어", short: "3형식", group: null, count: 8 },
  { id: "structure-4", sectionId: "structure", kind: "basic", title: "4형식 — 주어 + 동사 + 두 개의 목적어", short: "4형식", group: null, count: 7 },
  { id: "structure-5", sectionId: "structure", kind: "basic", title: "5형식 — 주어 + 동사 + 목적어 + 목적격보어", short: "5형식", group: null, count: 7 },
  { id: "structure-review", sectionId: "structure", kind: "review", title: "문장 5형식 통합 정리", short: "통합정리", group: null, count: 12 },
  { id: "tense-prog", sectionId: "tense2", kind: "basic", title: "진행시제 — 진행 중인 동작", short: "진행", group: null, count: 7 },
  { id: "present-perfect", sectionId: "tense2", kind: "basic", title: "현재완료 — have/has + p.p", short: "현재완료", group: null, count: 7 },
  { id: "past-perfect", sectionId: "tense2", kind: "basic", title: "과거완료 — had + p.p", short: "과거완료", group: null, count: 6 },
  { id: "future-perfect-progressive", sectionId: "tense2", kind: "basic", title: "미래완료 · 완료진행", short: "미래완료", group: null, count: 7 },
  { id: "tense2-review", sectionId: "tense2", kind: "review", title: "진행·완료 통합 정리", short: "통합정리", group: null, count: 11 },
  { id: "tense-all-mega", sectionId: "tense2", kind: "mega", title: "전체 시제 대왕정리", short: "전체 총정리", group: null, count: 12 },
  { id: "to-infinitive", sectionId: "verbal", kind: "basic", title: "to부정사 — to + 동사원형", short: "to부정사", group: null, count: 7 },
  { id: "gerund", sectionId: "verbal", kind: "basic", title: "동명사 — V-ing의 명사 역할", short: "동명사", group: null, count: 7 },
  { id: "participle", sectionId: "verbal", kind: "basic", title: "분사 — 동사가 형용사 역할", short: "분사", group: null, count: 8 },
  { id: "participial-construction", sectionId: "verbal", kind: "basic", title: "분사구문 — 부사절을 분사로 압축", short: "분사구문", group: null, count: 8 },
  { id: "verbal-advanced", sectionId: "verbal", kind: "basic", title: "준동사 심화 — 의미상 주어·완료형·가주어/가목적어", short: "심화", group: null, count: 8 },
  { id: "verbal-review", sectionId: "verbal", kind: "review", title: "준동사 통합 정리", short: "통합정리", group: null, count: 12 },
  { id: "relative-pronoun", sectionId: "relative", kind: "basic", title: "관계대명사 — who, which, that, whose, whom", short: "관계대명사", group: null, count: 7 },
  { id: "relative-adverb", sectionId: "relative", kind: "basic", title: "관계부사 — when, where, why, how", short: "관계부사", group: null, count: 7 },
  { id: "what-usage", sectionId: "relative", kind: "basic", title: "what 총정리 — 다양한 용법", short: "what 총정리", group: null, count: 8 },
  { id: "relative-advanced", sectionId: "relative", kind: "basic", title: "관계사 심화 — 계속적 용법·생략·복합관계사", short: "심화", group: null, count: 7 },
  { id: "relative-review", sectionId: "relative", kind: "review", title: "관계사 통합 정리", short: "통합정리", group: null, count: 11 },
  { id: "subjunctive", sectionId: "advanced", kind: "basic", title: "가정법 — 사실의 반대 또는 바람", short: "기본", group: "가정법", count: 8 },
  { id: "subjunctive-future", sectionId: "advanced", kind: "basic", title: "가정법 미래 — 일어날 가능성이 낮은 미래", short: "미래", group: "가정법", count: 7 },
  { id: "comparison", sectionId: "advanced", kind: "basic", title: "비교 구문 — 비교급·최상급·as ~ as", short: "비교 구문", group: null, count: 8 },
  { id: "noun-clause", sectionId: "advanced", kind: "basic", title: "명사절 — 문장 안의 문장", short: "명사절", group: null, count: 8 },
  { id: "reported-speech", sectionId: "advanced", kind: "basic", title: "화법 — 직접화법과 간접화법", short: "화법", group: null, count: 7 },
  { id: "special-structure", sectionId: "advanced", kind: "basic", title: "특수구문 — 강조·도치·so~that·so do I", short: "특수구문", group: null, count: 9 },
  { id: "negation", sectionId: "advanced", kind: "basic", title: "부정 표현 — 부분부정과 전체부정", short: "부정 표현", group: null, count: 8 },
  { id: "advanced-review", sectionId: "advanced", kind: "review", title: "고급 표현 통합 정리", short: "통합정리", group: null, count: 12 },
];
