// 자동 생성 파일 — 직접 고치지 말 것. `npm run check` 가 다시 만든다.
// 홈 화면이 큰 콘텐츠 청크를 기다리지 않고 목차를 그리기 위한 메타데이터.

export const MANIFEST = [
  { id: "be-aff", sectionId: "tense", kind: "basic", title: "be동사 긍정", blurb: "I am, You are, He is...", count: 10 },
  { id: "be-neg", sectionId: "tense", kind: "basic", title: "be동사 부정", blurb: "be동사 + not", count: 8 },
  { id: "be-q", sectionId: "tense", kind: "basic", title: "be동사 의문", blurb: "be동사 + 주어 ~?", count: 7 },
  { id: "be-negq", sectionId: "tense", kind: "basic", title: "be동사 부정의문", blurb: "Isn't ... ? / Aren't ... ?", count: 6 },
  { id: "be-review", sectionId: "tense", kind: "review", title: "be동사 통합 정리", blurb: "긍정·부정·의문·부정의문 한꺼번에", count: 11 },
  { id: "do-aff", sectionId: "tense", kind: "basic", title: "일반동사 긍정", blurb: "동사원형 / 3인칭 단수 -s", count: 8 },
  { id: "do-neg", sectionId: "tense", kind: "basic", title: "일반동사 부정", blurb: "don't / doesn't + 동사원형", count: 6 },
  { id: "do-q", sectionId: "tense", kind: "basic", title: "일반동사 의문", blurb: "Do / Does + 주어 + 동사원형 ?", count: 6 },
  { id: "do-negq", sectionId: "tense", kind: "basic", title: "일반동사 부정의문", blurb: "Don't / Doesn't + 주어 ~?", count: 6 },
  { id: "do-review", sectionId: "tense", kind: "review", title: "일반동사 통합 정리", blurb: "긍정·부정·의문·부정의문 한꺼번에", count: 11 },
  { id: "present-mega", sectionId: "tense", kind: "mega", title: "현재시제 대왕 정리", blurb: "be동사 vs 일반동사 — 한 챕터에서 끝내기", count: 12 },
  { id: "be-past", sectionId: "tense", kind: "basic", title: "be동사 과거", blurb: "was / were", count: 6 },
  { id: "do-past", sectionId: "tense", kind: "basic", title: "일반동사 과거", blurb: "동사 + -ed / 불규칙 변화", count: 7 },
  { id: "past-review", sectionId: "tense", kind: "review", title: "과거시제 정리", blurb: "was/were vs did + 원형", count: 10 },
  { id: "be-future", sectionId: "tense", kind: "basic", title: "be동사 미래", blurb: "will be / be going to be", count: 5 },
  { id: "do-future", sectionId: "tense", kind: "basic", title: "일반동사 미래", blurb: "will + 동사원형", count: 6 },
  { id: "future-review", sectionId: "tense", kind: "review", title: "미래시제 정리", blurb: "will + 원형 — be든 일반이든 항상 원형", count: 10 },
  { id: "all-mega", sectionId: "tense", kind: "mega", title: "현재·과거·미래 대왕 정리", blurb: "세 시제를 한 챕터에서 마스터하기", count: 12 },
  { id: "passive-basic", sectionId: "passive", kind: "basic", title: "수동태 기본", blurb: "be + 과거분사 (p.p)", count: 8 },
  { id: "passive-negq", sectionId: "passive", kind: "basic", title: "수동태 부정·의문", blurb: "be동사처럼 다룬다", count: 6 },
  { id: "passive-45", sectionId: "passive", kind: "basic", title: "4·5형식 수동태", blurb: "두 개의 목적어·목적격보어가 있는 문장의 수동 전환", count: 7 },
  { id: "passive-advanced", sectionId: "passive", kind: "basic", title: "심화 수동태 — 시제·조동사·동사구·by 이외 전치사", blurb: "진행형·완료형 수동태, 관용 전치사(be interested in 등)", count: 7 },
  { id: "passive-review", sectionId: "passive", kind: "review", title: "수동태 통합 정리", blurb: "능동 ↔ 수동, 시제별 한꺼번에", count: 11 },
  { id: "noun", sectionId: "parts", kind: "basic", title: "명사 — 셀 수 있는/없는", blurb: "a / an / -s / 셀 수 없는 명사", count: 8 },
  { id: "adjective", sectionId: "parts", kind: "basic", title: "형용사 — 명사를 꾸민다", blurb: "명사 앞, be동사 뒤", count: 8 },
  { id: "adverb", sectionId: "parts", kind: "basic", title: "부사 — 동사를 꾸민다", blurb: "동사·형용사·부사·문장 전체를 꾸미기", count: 8 },
  { id: "parts-review", sectionId: "parts", kind: "review", title: "품사 통합 정리", blurb: "명사·형용사·부사 헷갈리지 않기", count: 11 },
  { id: "conjunction", sectionId: "connect", kind: "basic", title: "접속사 — 단어·문장을 잇다", blurb: "and / but / or / because / when / if", count: 8 },
  { id: "preposition", sectionId: "connect", kind: "basic", title: "전치사 — 시간·장소를 표시", blurb: "in / on / at / to / from", count: 9 },
  { id: "modal", sectionId: "connect", kind: "basic", title: "조동사 — 동사에 의미를 더한다", blurb: "can / will / must / should / may", count: 8 },
  { id: "modal-have-pp", sectionId: "connect", kind: "basic", title: "조동사 + have + p.p — 과거에 대한 추측·후회", blurb: "should have / must have / could have — 지나간 일에 대한 판단", count: 7 },
  { id: "modal-idioms", sectionId: "connect", kind: "basic", title: "조동사 관용 — have to · ought to · used to 등", blurb: "must 옆 have to / should 옆 ought to / 과거 습관 used to", count: 7 },
  { id: "adverb-clause", sectionId: "connect", kind: "basic", title: "부사절 접속사 심화 — 양보·조건·목적·시간", blurb: "although / unless / so that / in case / by the time", count: 7 },
  { id: "connect-review", sectionId: "connect", kind: "review", title: "접속사·전치사·조동사 통합 정리", blurb: "헷갈리는 짝꿍들 한 번에", count: 12 },
  { id: "structure-1", sectionId: "structure", kind: "basic", title: "1형식 — 주어 + 동사", blurb: "S + V — 동사만으로 의미가 완성", count: 7 },
  { id: "structure-2", sectionId: "structure", kind: "basic", title: "2형식 — 주어 + 동사 + 보어", blurb: "S + V + SC — 주어의 상태를 설명 (S = SC)", count: 7 },
  { id: "structure-3", sectionId: "structure", kind: "basic", title: "3형식 — 주어 + 동사 + 목적어", blurb: "S + V + O — 동작이 미치는 대상이 있는 가장 흔한 구조", count: 8 },
  { id: "structure-4", sectionId: "structure", kind: "basic", title: "4형식 — 주어 + 동사 + 두 개의 목적어", blurb: "S + V + IO + DO — ~에게(IO) ~을(DO) 주다·말하다·보여주다", count: 7 },
  { id: "structure-5", sectionId: "structure", kind: "basic", title: "5형식 — 주어 + 동사 + 목적어 + 목적격보어", blurb: "S + V + O + OC — 목적어를 어떤 상태로 만들거나, 어떻게 부르다 (O = OC)", count: 7 },
  { id: "structure-review", sectionId: "structure", kind: "review", title: "문장 5형식 통합 정리", blurb: "1형식부터 5형식까지 — 구조 식별 종합", count: 12 },
  { id: "tense-prog", sectionId: "tense2", kind: "basic", title: "진행시제 — 진행 중인 동작", blurb: "be + V-ing — 어떤 시점에 진행 중", count: 7 },
  { id: "present-perfect", sectionId: "tense2", kind: "basic", title: "현재완료 — have/has + p.p", blurb: "과거의 일이 현재까지 이어지거나 영향을 미침", count: 7 },
  { id: "past-perfect", sectionId: "tense2", kind: "basic", title: "과거완료 — had + p.p", blurb: "과거의 한 시점보다 더 이전 (대과거)", count: 6 },
  { id: "future-perfect-progressive", sectionId: "tense2", kind: "basic", title: "미래완료 · 완료진행", blurb: "will have p.p / have been V-ing — 시제의 마지막 조각", count: 7 },
  { id: "tense2-review", sectionId: "tense2", kind: "review", title: "진행·완료 통합 정리", blurb: "진행시제와 완료시제 종합", count: 11 },
  { id: "tense-all-mega", sectionId: "tense2", kind: "mega", title: "전체 시제 대왕정리", blurb: "단순 · 진행 · 완료 — 모든 시제 종합", count: 12 },
  { id: "to-infinitive", sectionId: "verbal", kind: "basic", title: "to부정사 — to + 동사원형", blurb: "동사를 명사·형용사·부사로 변신시키는 기본기", count: 7 },
  { id: "gerund", sectionId: "verbal", kind: "basic", title: "동명사 — V-ing의 명사 역할", blurb: "동사ing가 명사 자리에 들어가는 경우", count: 7 },
  { id: "participle", sectionId: "verbal", kind: "basic", title: "분사 — 동사가 형용사 역할", blurb: "현재분사(~ing)와 과거분사(p.p)로 명사 꾸미기", count: 8 },
  { id: "participial-construction", sectionId: "verbal", kind: "basic", title: "분사구문 — 부사절을 분사로 압축", blurb: "When/Because/If ~를 V-ing 하나로 줄이는 고급 표현", count: 8 },
  { id: "verbal-advanced", sectionId: "verbal", kind: "basic", title: "준동사 심화 — 의미상 주어·완료형·가주어/가목적어", blurb: "for me to / of you to / to have p.p / It ~ to부정사", count: 8 },
  { id: "verbal-review", sectionId: "verbal", kind: "review", title: "준동사 통합 정리", blurb: "to부정사 · 동명사 · 분사 종합", count: 12 },
  { id: "relative-pronoun", sectionId: "relative", kind: "basic", title: "관계대명사 — who, which, that, whose, whom", blurb: "두 문장을 하나로 — 명사를 받아 잇는 다리", count: 7 },
  { id: "relative-adverb", sectionId: "relative", kind: "basic", title: "관계부사 — when, where, why, how", blurb: "시간·장소·이유·방법을 받아 잇는 관계사", count: 7 },
  { id: "what-usage", sectionId: "relative", kind: "basic", title: "what 총정리 — 다양한 용법", blurb: "관계대명사 what · 감탄문 · what + 명사 — 헷갈리는 what 정리", count: 8 },
  { id: "relative-advanced", sectionId: "relative", kind: "basic", title: "관계사 심화 — 계속적 용법·생략·복합관계사", blurb: ", who / 관계사 생략 / whoever·whatever·however", count: 7 },
  { id: "relative-review", sectionId: "relative", kind: "review", title: "관계사 통합 정리", blurb: "관계대명사 · 관계부사 종합", count: 11 },
  { id: "subjunctive", sectionId: "advanced", kind: "basic", title: "가정법 — 사실의 반대 또는 바람", blurb: "If I were... / If I had... — 현실과 다른 상황을 말할 때", count: 8 },
  { id: "subjunctive-future", sectionId: "advanced", kind: "basic", title: "가정법 미래 — 일어날 가능성이 낮은 미래", blurb: "If ~ were to / If ~ should — 거의 불가능하거나 가능성 낮은 미래 가정", count: 7 },
  { id: "comparison", sectionId: "advanced", kind: "basic", title: "비교 구문 — 비교급·최상급·as ~ as", blurb: "더 ~한 / 가장 ~한 / ~만큼 ~한", count: 8 },
  { id: "noun-clause", sectionId: "advanced", kind: "basic", title: "명사절 — 문장 안의 문장", blurb: "that / whether(if) / 의문사 — 문장이 통째로 명사 역할", count: 8 },
  { id: "reported-speech", sectionId: "advanced", kind: "basic", title: "화법 — 직접화법과 간접화법", blurb: "He said \"I am happy.\" → He said (that) he was happy.", count: 7 },
  { id: "special-structure", sectionId: "advanced", kind: "basic", title: "특수구문 — 강조·도치·so~that·so do I", blurb: "어순을 바꾸거나 의미를 강조하는 표현들", count: 9 },
  { id: "negation", sectionId: "advanced", kind: "basic", title: "부정 표현 — 부분부정과 전체부정", blurb: "not always ~한 건 아니다 / no one 아무도 아니다", count: 8 },
  { id: "advanced-review", sectionId: "advanced", kind: "review", title: "고급 표현 통합 정리", blurb: "가정법 · 비교 · 특수구문 종합", count: 12 },
];
