// part3Parts — 콘텐츠 파일. 형식은 src/content/schema.js 참고.

export const part3Parts = [
  {
    id: "noun",
    title: "명사 — 셀 수 있는/없는",
    kind: "basic",
    blurb: "a / an / -s / 셀 수 없는 명사",
    summary: [
      { t: "h", text: "명사의 종류" },
      {
        t: "table",
        head: ["종류", "특징", "예시"],
        rows: [
          ["셀 수 있는 단수", "앞에 <b>a / an</b>", "<b>a</b> book, <b>an</b> apple"],
          ["셀 수 있는 복수", "끝에 <b>-s / -es</b>", "book<b>s</b>, box<b>es</b>"],
          ["셀 수 없는", "관사 ✕, 복수 ✕", "water, milk, money, love"],
        ],
      },
      { t: "h", text: "a 와 an" },
      { t: "p", text: "• 자음 소리 앞: <code>a book</code>, <code>a university</code> (yu- 소리)<br> • 모음 소리 앞: <code>an apple</code>, <code>an hour</code> (h 묵음)" },
      { t: "h", text: "불규칙 복수" },
      { t: "p", text: "man → <b>men</b>, woman → <b>women</b>, child → <b>children</b>, foot → <b>feet</b>, tooth → <b>teeth</b>" },
      { t: "h", text: "셀 수 없는 명사의 양" },
      { t: "p", text: "a glass <b>of</b> water, a piece <b>of</b> bread, a lot <b>of</b> money" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 사과 하나를 가지고 있다.",
        prefix: ["I", "have"],
        answer: ["an apple"],
        suffix: ["."],
        distractors: ["a apple", "the apples", "apple", "an apples"],
        explanation: "모음 소리(a-) 앞에는 <code>an</code>. 단수 → <code>apple</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 책 세 권을 가지고 있다.",
        prefix: ["She", "has"],
        answer: ["three", "books"],
        suffix: ["."],
        distractors: ["three book", "a books", "the book", "three a books"],
        explanation: "셀 수 있는 명사 복수 → <code>books</code>. 숫자 뒤에는 관사 ✕.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "물 좀 마실래?",
        prefix: ["Do", "you", "want"],
        answer: ["some", "water"],
        suffix: ["?"],
        distractors: ["a water", "some waters", "an water", "the waters"],
        explanation: "<b>water</b>는 셀 수 없는 명사 → 관사 ✕, 복수형 ✕. 양은 <code>some</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "한 시간만 기다려.",
        prefix: ["Wait"],
        answer: ["an hour"],
        suffix: ["."],
        distractors: ["a hour", "hour", "the hour", "an hours"],
        explanation: "<b>hour</b>의 h는 묵음 → 모음 소리 → <code>an hour</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "아이들이 공원에서 논다.",
        prefix: ["The"],
        answer: ["children"],
        suffix: ["play", "in", "the", "park", "."],
        distractors: ["childs", "child", "a children", "childrens"],
        explanation: "<b>child</b>의 불규칙 복수 → <code>children</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그는 대학생이다.",
        prefix: ["He", "is"],
        answer: ["a university"],
        suffix: ["student", "."],
        distractors: ["an university", "the university", "university", "an universities"],
        explanation: "<b>university</b>의 발음은 /yu-/ — 자음 소리 → <code>a</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "빵 한 조각 주세요.",
        prefix: ["Give", "me"],
        answer: ["a piece"],
        suffix: ["of", "bread", "."],
        distractors: ["a bread", "the bread", "a pieces", "piece"],
        explanation: "셀 수 없는 명사의 양 → <code>a piece of bread</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "두 명의 여자가 노래를 부른다.",
        prefix: ["Two"],
        answer: ["women"],
        suffix: ["sing", "."],
        distractors: ["woman", "womans", "a women", "the woman"],
        explanation: "<b>woman</b>의 불규칙 복수 → <code>women</code>.",
      },
    ],
  },

  {
    id: "adjective",
    title: "형용사 — 명사를 꾸민다",
    kind: "basic",
    blurb: "명사 앞, be동사 뒤",
    summary: [
      { t: "h", text: "형용사의 위치 두 가지" },
      { t: "p", text: "1) <b>명사 앞</b>에서 꾸미기 (한정적 용법)<br> 예: a <b>beautiful</b> flower / a <b>tall</b> boy" },
      { t: "p", text: "2) <b>be동사 / 감각동사 뒤</b>에서 보충 설명 (서술적 용법)<br> 예: She is <b>kind</b>. / The soup smells <b>good</b>." },
      { t: "h", text: "형용사를 만드는 흔한 어미" },
      { t: "p", text: "-ful (beautiful, useful), -less (useless, careless),<br> -ous (famous, dangerous), -y (happy, rainy),<br> -ive (active, creative), -al (national, special)" },
      { t: "h", text: "형용사 순서" },
      { t: "p", text: "여러 형용사가 올 때: <b>의견 → 크기 → 나이 → 색 → 출신 → 재료 → 명사</b><br> 예: a <b>beautiful small old</b> house" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그것은 아름다운 꽃이다.",
        prefix: ["It", "is"],
        answer: ["a", "beautiful", "flower"],
        suffix: ["."],
        distractors: ["beautiful a flower", "a flower beautiful", "flower a beautiful", "beautifully a flower"],
        explanation: "<code>a + 형용사 + 명사</code> — 형용사는 명사 앞.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 친절하다.",
        prefix: ["She"],
        answer: ["is", "kind"],
        suffix: ["."],
        distractors: ["kind is", "is kindly", "are kind", "is a kind"],
        explanation: "be동사 뒤에 형용사로 보충 설명 → <code>is kind</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "이 수프는 좋은 냄새가 난다.",
        prefix: ["This", "soup", "smells"],
        answer: ["good"],
        suffix: ["."],
        distractors: ["well", "goodly", "a good", "better"],
        explanation: "감각동사 <b>smell</b> 뒤에는 <b>형용사</b> → <code>good</code>. (well은 부사)",
      },
      {
        id: "q4",
        type: "blank",
        ko: "나는 행복한 강아지를 봤다.",
        prefix: ["I", "saw"],
        answer: ["a", "happy", "dog"],
        suffix: ["."],
        distractors: ["happily a dog", "dog a happy", "a dog happy", "happy a dog"],
        explanation: "<code>a + 형용사 + 명사</code> 순.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그 영화는 재미있었다.",
        prefix: ["The", "movie"],
        answer: ["was", "interesting"],
        suffix: ["."],
        distractors: ["interesting was", "was interestingly", "is interesting", "were interesting"],
        explanation: "be동사 과거 + 형용사 → <code>was interesting</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그는 유명한 가수이다.",
        prefix: ["He", "is"],
        answer: ["a", "famous", "singer"],
        suffix: ["."],
        distractors: ["famous a singer", "singer a famous", "a singer famous", "famously a singer"],
        explanation: "<code>a + 형용사 + 명사</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그 가방은 무겁다.",
        prefix: ["The", "bag"],
        answer: ["is", "heavy"],
        suffix: ["."],
        distractors: ["heavy is", "is heavily", "are heavy", "heavily"],
        explanation: "be동사 뒤 형용사 → <code>is heavy</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "오늘은 화창한 날이다.",
        prefix: ["It", "is"],
        answer: ["a", "sunny", "day"],
        suffix: ["."],
        distractors: ["sunny a day", "a day sunny", "day a sunny", "sun a day"],
        explanation: "날씨 표현 — <code>It is a + 형용사 + day</code>.",
      },
    ],
  },

  {
    id: "adverb",
    title: "부사 — 동사를 꾸민다",
    kind: "basic",
    blurb: "동사·형용사·부사·문장 전체를 꾸미기",
    summary: [
      { t: "h", text: "부사가 꾸미는 것" },
      { t: "p", text: "• <b>동사</b>: He runs <b>fast</b>.<br> • <b>형용사</b>: She is <b>very</b> kind.<br> • <b>다른 부사</b>: He runs <b>very</b> fast.<br> • <b>문장 전체</b>: <b>Fortunately</b>, he is safe." },
      { t: "h", text: "형용사 → 부사 만들기" },
      {
        t: "table",
        head: ["규칙", "형용사", "부사"],
        rows: [
          ["대부분: +ly", "quick, slow", "quick<b>ly</b>, slow<b>ly</b>"],
          ["자음+y: y→i+ly", "happy, easy", "happ<b>ily</b>, eas<b>ily</b>"],
          ["-le → -ly", "simple, gentle", "simp<b>ly</b>, gent<b>ly</b>"],
        ],
      },
      { t: "h", text: "형용사·부사 형태가 같은 단어 ⚠️" },
      { t: "p", text: "fast, hard, late, early, high, low — 형태 그대로!<br> <b>주의: hardly</b>는 \"거의 ~않다\"라는 <u>전혀 다른 뜻</u>." },
      { t: "h", text: "빈도부사 (얼마나 자주)" },
      { t: "p", text: "always &gt; usually &gt; often &gt; sometimes &gt; never<br> 자리: <b>be동사 뒤</b> / <b>일반동사 앞</b><br> 예: She is <b>always</b> kind. / She <b>always</b> studies hard." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그는 빨리 달린다.",
        prefix: ["He", "runs"],
        answer: ["fast"],
        suffix: ["."],
        distractors: ["fastly", "a fast", "faster", "fasted"],
        explanation: "<b>fast</b>는 형용사·부사 형태가 같음. <s>fastly</s>는 없는 단어!",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 행복하게 노래한다.",
        prefix: ["She", "sings"],
        answer: ["happily"],
        suffix: ["."],
        distractors: ["happy", "happyly", "happiness", "happier"],
        explanation: "<b>happy</b>의 부사형 → 자음+y는 y→i+ly → <code>happily</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그것은 매우 비싸다.",
        prefix: ["It", "is"],
        answer: ["very", "expensive"],
        suffix: ["."],
        distractors: ["expensive very", "a very expensive", "very a expensive", "expensively very"],
        explanation: "<b>very</b>는 형용사를 꾸미는 부사 → <code>very + 형용사</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그는 항상 늦는다.",
        prefix: ["He", "is"],
        answer: ["always", "late"],
        suffix: ["."],
        distractors: ["late always", "always a late", "a late always", "lately always"],
        explanation: "빈도부사는 <b>be동사 뒤</b> → <code>is + always + late</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그녀는 항상 일찍 일어난다.",
        prefix: ["She"],
        answer: ["always", "gets"],
        suffix: ["up", "early", "."],
        distractors: ["gets always", "is always get", "always is get", "always get"],
        explanation: "빈도부사는 <b>일반동사 앞</b> → <code>always + gets</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그는 조용히 말했다.",
        prefix: ["He", "spoke"],
        answer: ["quietly"],
        suffix: ["."],
        distractors: ["quiet", "quietyly", "a quiet", "quieted"],
        explanation: "<b>quiet</b>의 부사형 → +ly → <code>quietly</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그 차는 정말 천천히 간다.",
        prefix: ["The", "car", "goes"],
        answer: ["very", "slowly"],
        suffix: ["."],
        distractors: ["slow very", "slowly very", "very slow", "slow"],
        explanation: "부사를 꾸미는 부사 → <code>very + slowly</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "다행히도, 그는 무사하다.",
        answer: ["Fortunately"],
        suffix: [",", "he", "is", "safe", "."],
        distractors: ["Fortunate", "Fortune", "Lucky", "Luckily a"],
        explanation: "문장 전체를 꾸미는 부사 → 문장 맨 앞 + 쉼표 → <code>Fortunately,</code>.",
      },
    ],
  },

  {
    id: "parts-review",
    title: "품사 통합 정리",
    kind: "review",
    blurb: "명사·형용사·부사 헷갈리지 않기",
    summary: [
      { t: "h", text: "세 품사를 한눈에" },
      {
        t: "table",
        head: ["품사", "역할", "위치"],
        rows: [
          ["명사", "사람·사물·개념의 이름", "주어 / 목적어 / 보어 자리"],
          ["형용사", "명사 꾸미기", "명사 앞 / be동사·감각동사 뒤"],
          ["부사", "동사·형용사·부사·문장 꾸미기", "비교적 자유로움"],
        ],
      },
      { t: "h", text: "가장 자주 틀리는 포인트" },
      { t: "p", text: "• be동사 뒤 → <b>형용사</b>: She is <b>happy</b>. (○) / She is <s>happily</s>. (✗)<br> • 일반동사 뒤 → <b>부사</b>: She sings <b>happily</b>. (○)<br> • 감각동사(look, smell, taste, sound, feel) 뒤 → <b>형용사</b>!" },
      { t: "h", text: "관사·복수 짧은 점검" },
      { t: "p", text: "• 셀 수 있는 단수 명사는 <b>혼자 못 다닌다</b> — <code>a/an/the/소유격/this/that</code>이 필요.<br> • 셀 수 없는 명사는 <b>관사·복수 ✕</b>." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그녀는 아름답게 노래한다.",
        prefix: ["She", "sings"],
        answer: ["beautifully"],
        suffix: ["."],
        distractors: ["beautiful", "beauty", "a beautiful", "beauties"],
        explanation: "동사 <b>sings</b>를 꾸미려면 <b>부사</b> → <code>beautifully</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그 음식은 좋은 맛이 난다.",
        prefix: ["The", "food", "tastes"],
        answer: ["good"],
        suffix: ["."],
        distractors: ["well", "a good", "goodly", "better"],
        explanation: "감각동사 <b>taste</b> 뒤에는 <b>형용사</b> → <code>good</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그는 오래된 친구이다.",
        prefix: ["He", "is"],
        answer: ["an", "old", "friend"],
        suffix: ["."],
        distractors: ["a old friend", "old a friend", "an a old friend", "an friend old"],
        explanation: "모음 소리 → <code>an</code>. 어순은 <code>관사+형용사+명사</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "나는 보통 일찍 자러 간다.",
        prefix: ["I"],
        answer: ["usually", "go"],
        suffix: ["to", "bed", "early", "."],
        distractors: ["go usually", "am usually go", "usually am go", "usual go"],
        explanation: "빈도부사는 일반동사 앞 → <code>usually + go</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그 아이들은 행복하다.",
        prefix: ["The", "children"],
        answer: ["are", "happy"],
        suffix: ["."],
        distractors: ["is happy", "are happily", "is happily", "are a happy"],
        explanation: "<b>children</b>은 복수 → <code>are</code>. be동사 뒤는 형용사 → <code>happy</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그것은 매우 어려운 시험이었다.",
        prefix: ["It", "was"],
        answer: ["a", "very", "difficult", "test"],
        suffix: ["."],
        distractors: ["very a difficult test", "a difficult very test", "very difficult a test", "a very difficulty test"],
        explanation: "<code>a + 부사 + 형용사 + 명사</code> 순.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그녀는 한 시간 후에 도착할 거야.",
        prefix: ["She", "will", "arrive", "in"],
        answer: ["an hour"],
        suffix: ["."],
        distractors: ["a hour", "an hours", "the hour", "hour"],
        explanation: "<b>hour</b>의 h 묵음 → 모음 소리 → <code>an hour</code>.",
      },
      {
        id: "c1",
        type: "choice",
        ko: "그는 조심스럽게 운전한다.",
        choices: ["careful", "carefully"],
        correct: 1,
        sentence: ["He drives", null, "."],
        explanation: "동사 <b>drives</b>를 꾸미므로 부사 <code>carefully</code>.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "나는 많은 정보가 필요하다.",
        choices: ["many", "much"],
        correct: 1,
        sentence: ["I need", null, "information", "."],
        explanation: "<b>information</b>은 셀 수 없는 명사 → <code>much</code>.",
      },
      {
        id: "e1",
        type: "error",
        ko: "그녀는 아름답게 노래한다.",
        tokens: ["She", "sings", "beautiful", "."],
        wrongIndex: 2,
        fix: "beautifully",
        explanation: "동사를 꾸밀 때는 부사 <code>beautifully</code>.",
      },
      {
        id: "e2",
        type: "error",
        ko: "나는 아이가 둘 있다.",
        tokens: ["I", "have", "two", "childs", "."],
        wrongIndex: 3,
        fix: "children",
        explanation: "<b>child</b>의 복수형은 불규칙 <code>children</code>.",
      },
    ],
  },
];
