// part1Tense — 콘텐츠 파일. 형식은 src/content/schema.js 참고.

export const part1Tense = [
  {
    id: "be-aff",
    title: "be동사 긍정",
    kind: "basic",
    blurb: "I am, You are, He is...",
    summary: [
      { t: "h", text: "be동사란?" },
      { t: "p", text: "be동사는 <b>주어의 상태</b>를 나타내는 동사입니다. <code>am / are / is</code> 세 가지 형태가 있어요." },
      {
        t: "table",
        head: ["주어", "be동사", "예시"],
        rows: [
          ["I", "<code>am</code>", "I <b>am</b> a student."],
          ["You / We / They / 복수명사", "<code>are</code>", "You <b>are</b> kind."],
          ["He / She / It / 단수명사", "<code>is</code>", "She <b>is</b> a teacher."],
        ],
      },
      { t: "h", text: "줄임말" },
      { t: "p", text: "<code>I am → I'm</code>, <code>You are → You're</code>, <code>He is → He's</code>" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 학생이다.",
        prefix: ["I"],
        answer: ["am"],
        suffix: ["a", "student", "."],
        distractors: ["is", "are", "be"],
        explanation: "주어가 <b>I</b>일 때 be동사는 <code>am</code>을 씁니다.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 친절하다.",
        prefix: ["She"],
        answer: ["is"],
        suffix: ["kind", "."],
        distractors: ["am", "are", "be"],
        explanation: "주어가 3인칭 단수(<b>She/He/It</b>)일 때는 <code>is</code>를 씁니다.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "우리는 친구이다.",
        prefix: ["We"],
        answer: ["are"],
        suffix: ["friends", "."],
        distractors: ["am", "is", "be"],
        explanation: "주어가 복수(<b>We/You/They</b>)일 때는 <code>are</code>를 씁니다.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그것은 책이다.",
        prefix: ["It"],
        answer: ["is"],
        suffix: ["a", "book", "."],
        distractors: ["am", "are", "be"],
        explanation: "<b>It</b>은 3인칭 단수이므로 <code>is</code>를 씁니다.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그들은 행복하다.",
        prefix: ["They"],
        answer: ["are"],
        suffix: ["happy", "."],
        distractors: ["am", "is", "be"],
        explanation: "<b>They</b>는 복수이므로 <code>are</code>를 씁니다.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "너는 똑똑하다.",
        prefix: ["You"],
        answer: ["are"],
        suffix: ["smart", "."],
        distractors: ["am", "is", "be"],
        explanation: "<b>You</b>는 단수/복수 모두 <code>are</code>를 씁니다.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "Tom은 의사이다.",
        prefix: ["Tom"],
        answer: ["is"],
        suffix: ["a", "doctor", "."],
        distractors: ["am", "are", "be"],
        explanation: "사람 이름은 3인칭 단수 — <code>is</code>를 씁니다.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "내 부모님은 선생님이시다.",
        prefix: ["My", "parents"],
        answer: ["are"],
        suffix: ["teachers", "."],
        distractors: ["am", "is", "be"],
        explanation: "<b>parents</b>는 복수 명사이므로 <code>are</code>를 씁니다.",
      },
      {
        id: "q9",
        type: "blank",
        ko: "이 가방은 무겁다.",
        prefix: ["This", "bag"],
        answer: ["is"],
        suffix: ["heavy", "."],
        distractors: ["am", "are", "be"],
        explanation: "<b>this + 단수명사</b>는 3인칭 단수입니다 → <code>is</code>.",
      },
      {
        id: "q10",
        type: "blank",
        ko: "나는 한국 출신이다.",
        prefix: ["I"],
        answer: ["am"],
        suffix: ["from", "Korea", "."],
        distractors: ["is", "are", "be"],
        explanation: "<b>I</b>의 짝꿍은 항상 <code>am</code>.",
      },
    ],
  },

  {
    id: "be-neg",
    title: "be동사 부정",
    kind: "basic",
    blurb: "be동사 + not",
    summary: [
      { t: "h", text: "be동사 부정문" },
      { t: "p", text: "be동사 부정문은 <b>be동사 뒤에 <code>not</code></b>을 붙입니다. 어순은 <code>주어 + be + not + 나머지</code>." },
      {
        t: "table",
        head: ["긍정", "부정", "줄임말"],
        rows: [
          ["I am", "I am not", "(I'm not)"],
          ["You are", "You are not", "You aren't"],
          ["He is", "He is not", "He isn't"],
        ],
      },
      { t: "p", text: "⚠️ <code>am not</code>은 줄여서 <code>amn't</code>로 쓰지 <b>않습니다</b>. <code>I'm not</code>만 가능해요." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그는 학생이 아니다.",
        prefix: ["He"],
        answer: ["is", "not"],
        suffix: ["a", "student", "."],
        distractors: ["are", "am", "no", "don't"],
        explanation: "be동사 부정은 <b>be + not</b>. <b>He</b>의 be동사는 <code>is</code> → <code>is not</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "나는 피곤하지 않다.",
        prefix: ["I"],
        answer: ["am", "not"],
        suffix: ["tired", "."],
        distractors: ["are", "is", "not am", "don't"],
        explanation: "<b>I</b>의 짝꿍은 <code>am</code>. 부정은 <code>am not</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그들은 한국인이 아니다.",
        prefix: ["They"],
        answer: ["are", "not"],
        suffix: ["Korean", "."],
        distractors: ["is", "am", "no", "isn't"],
        explanation: "<b>They</b>는 복수 → <code>are not</code>. 줄임말로는 <code>aren't</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그것은 내 것이 아니다.",
        prefix: ["It"],
        answer: ["is", "not"],
        suffix: ["mine", "."],
        distractors: ["are", "am", "no", "doesn't"],
        explanation: "<b>It</b>은 3인칭 단수 → <code>is not</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "우리는 늦지 않았다.",
        prefix: ["We"],
        answer: ["are", "not"],
        suffix: ["late", "."],
        distractors: ["is", "am", "no", "don't"],
        explanation: "<b>We</b>는 복수 → <code>are not</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "이 영화는 재미있지 않다.",
        prefix: ["This", "movie"],
        answer: ["is", "not"],
        suffix: ["interesting", "."],
        distractors: ["are", "am", "no", "doesn't"],
        explanation: "<b>this + 단수</b> → 3인칭 단수 → <code>is not</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "너는 혼자가 아니다.",
        prefix: ["You"],
        answer: ["are", "not"],
        suffix: ["alone", "."],
        distractors: ["is", "am", "no", "don't"],
        explanation: "<b>You</b>의 be동사는 <code>are</code>. 부정은 <code>are not</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "내 여동생은 키가 크지 않다.",
        prefix: ["My", "sister"],
        answer: ["is", "not"],
        suffix: ["tall", "."],
        distractors: ["are", "am", "no", "doesn't"],
        explanation: "<b>sister</b>는 단수 → <code>is not</code>.",
      },
    ],
  },

  {
    id: "be-q",
    title: "be동사 의문",
    kind: "basic",
    blurb: "be동사 + 주어 ~?",
    summary: [
      { t: "h", text: "be동사 의문문" },
      { t: "p", text: "be동사를 <b>주어 앞으로</b> 보냅니다. 끝에는 <code>?</code>." },
      { t: "p", text: "어순: <code>be동사 + 주어 + 나머지 ?</code>" },
      {
        t: "table",
        head: ["평서문", "의문문"],
        rows: [
          ["You are happy.", "<b>Are</b> you happy?"],
          ["He is a doctor.", "<b>Is</b> he a doctor?"],
          ["I am late.", "<b>Am</b> I late?"],
        ],
      },
      { t: "h", text: "대답" },
      { t: "p", text: "Yes, 주어 + be동사. / No, 주어 + be동사 + not." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "너는 학생이니?",
        answer: ["Are"],
        suffix: ["you", "a", "student", "?"],
        distractors: ["Is", "Am", "Do", "Does"],
        explanation: "<b>You</b>의 be동사는 <code>are</code>. 의문문은 주어 앞으로 → <code>Are you ...?</code>",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그는 한국 출신이니?",
        answer: ["Is"],
        suffix: ["he", "from", "Korea", "?"],
        distractors: ["Are", "Am", "Do", "Does"],
        explanation: "<b>He</b>는 3인칭 단수 → <code>Is he ...?</code>",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그들은 행복하니?",
        answer: ["Are"],
        suffix: ["they", "happy", "?"],
        distractors: ["Is", "Am", "Do", "Does"],
        explanation: "<b>They</b>는 복수 → <code>Are they ...?</code>",
      },
      {
        id: "q4",
        type: "blank",
        ko: "내가 늦었니?",
        answer: ["Am"],
        suffix: ["I", "late", "?"],
        distractors: ["Is", "Are", "Do", "Does"],
        explanation: "<b>I</b>의 be동사는 <code>am</code> → <code>Am I ...?</code>",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그것은 비싸니?",
        answer: ["Is"],
        suffix: ["it", "expensive", "?"],
        distractors: ["Are", "Am", "Do", "Does"],
        explanation: "<b>It</b>은 3인칭 단수 → <code>Is it ...?</code>",
      },
      {
        id: "q6",
        type: "blank",
        ko: "너희들은 준비됐니?",
        answer: ["Are"],
        suffix: ["you", "ready", "?"],
        distractors: ["Is", "Am", "Do", "Does"],
        explanation: "<b>you</b>는 단수/복수 모두 <code>are</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "이 책들은 새것이니?",
        answer: ["Are"],
        suffix: ["these", "books", "new", "?"],
        distractors: ["Is", "Am", "Do", "Does"],
        explanation: "<b>these books</b>는 복수 → <code>are</code>.",
      },
    ],
  },

  {
    id: "be-negq",
    title: "be동사 부정의문",
    kind: "basic",
    blurb: "Isn't ... ? / Aren't ... ?",
    summary: [
      { t: "h", text: "be동사 부정의문문" },
      { t: "p", text: "\"~하지 않니?\"라고 묻는 형태. <b>줄임말</b>을 주어 앞에 둡니다." },
      { t: "p", text: "어순: <code>Aren't / Isn't / Am I not + 주어 + 나머지 ?</code>" },
      {
        t: "table",
        head: ["긍정의문", "부정의문"],
        rows: [
          ["Are you tired?", "<b>Aren't</b> you tired?"],
          ["Is he home?", "<b>Isn't</b> he home?"],
          ["Am I right?", "<b>Am I not</b> right? (Aren't I ...?)"],
        ],
      },
      { t: "p", text: "💡 부정의문문에 대답할 때는 <b>사실 그대로</b>: 사실이면 Yes, 아니면 No." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "너 피곤하지 않니?",
        answer: ["Aren't"],
        suffix: ["you", "tired", "?"],
        distractors: ["Isn't", "Don't", "Doesn't", "Not"],
        explanation: "<b>you</b> → <code>are</code>의 줄임 부정 <code>aren't</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 의사 아니니?",
        answer: ["Isn't"],
        suffix: ["she", "a", "doctor", "?"],
        distractors: ["Aren't", "Don't", "Doesn't", "Not"],
        explanation: "<b>she</b> → <code>is</code>의 줄임 부정 <code>isn't</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그것은 사실이 아니니?",
        answer: ["Isn't"],
        suffix: ["it", "true", "?"],
        distractors: ["Aren't", "Don't", "Doesn't", "Not"],
        explanation: "<b>it</b> → <code>isn't</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그들은 친구 아니니?",
        answer: ["Aren't"],
        suffix: ["they", "friends", "?"],
        distractors: ["Isn't", "Don't", "Doesn't", "Not"],
        explanation: "<b>they</b> → <code>aren't</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "우리 늦은 거 아니니?",
        answer: ["Aren't"],
        suffix: ["we", "late", "?"],
        distractors: ["Isn't", "Don't", "Doesn't", "Not"],
        explanation: "<b>we</b> → <code>aren't</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "이거 네 거 아니니?",
        answer: ["Isn't"],
        suffix: ["this", "yours", "?"],
        distractors: ["Aren't", "Don't", "Doesn't", "Not"],
        explanation: "<b>this</b>(단수) → <code>isn't</code>.",
      },
    ],
  },

  {
    id: "be-review",
    title: "be동사 통합 정리",
    kind: "review",
    blurb: "긍정·부정·의문·부정의문 한꺼번에",
    summary: [
      { t: "h", text: "be동사 4가지 형태 한눈에" },
      {
        t: "table",
        head: ["형태", "어순", "예시 (He)"],
        rows: [
          ["긍정", "주어 + be", "He <b>is</b> tall."],
          ["부정", "주어 + be + not", "He <b>is not</b> tall."],
          ["의문", "be + 주어 ?", "<b>Is</b> he tall?"],
          ["부정의문", "be+not 줄임 + 주어 ?", "<b>Isn't</b> he tall?"],
        ],
      },
      { t: "p", text: "💡 핵심은 <b>be동사의 위치</b>입니다: 평서문은 주어 뒤, 의문문은 주어 앞." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그녀는 의사이다.",
        prefix: ["She"],
        answer: ["is"],
        suffix: ["a", "doctor", "."],
        distractors: ["am", "are", "isn't"],
        explanation: "긍정 + 3인칭 단수 → <code>is</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그들은 학생이 아니다.",
        prefix: ["They"],
        answer: ["are", "not"],
        suffix: ["students", "."],
        distractors: ["is", "am", "isn't", "don't"],
        explanation: "부정 + 복수 → <code>are not</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "너는 행복하니?",
        answer: ["Are"],
        suffix: ["you", "happy", "?"],
        distractors: ["Is", "Am", "Do"],
        explanation: "의문 + you → <code>Are you ...?</code>",
      },
      {
        id: "q4",
        type: "blank",
        ko: "이거 네 책이 아니니?",
        answer: ["Isn't"],
        suffix: ["this", "your", "book", "?"],
        distractors: ["Aren't", "Don't", "Doesn't"],
        explanation: "부정의문 + 단수 → <code>Isn't</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "나는 화나지 않았다.",
        prefix: ["I"],
        answer: ["am", "not"],
        suffix: ["angry", "."],
        distractors: ["are", "is", "don't"],
        explanation: "부정 + I → <code>am not</code>. (줄임은 <code>I'm not</code>만 가능)",
      },
      {
        id: "q6",
        type: "blank",
        ko: "내 부모님은 한국 출신이시다.",
        prefix: ["My", "parents"],
        answer: ["are"],
        suffix: ["from", "Korea", "."],
        distractors: ["is", "am", "be"],
        explanation: "복수 명사 → <code>are</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그는 너의 형 아니니?",
        answer: ["Isn't"],
        suffix: ["he", "your", "brother", "?"],
        distractors: ["Aren't", "Don't", "Doesn't"],
        explanation: "부정의문 + he → <code>Isn't</code>.",
      },
      {
        id: "c1",
        type: "choice",
        ko: "그녀는 나의 선생님이 아니다.",
        choices: ["isn't", "aren't"],
        correct: 0,
        sentence: ["She", null, "my teacher", "."],
        explanation: "주어가 3인칭 단수 <b>She</b> → <code>is not / isn't</code>.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "그들은 어제 바빴다.",
        choices: ["was", "were"],
        correct: 1,
        sentence: ["They", null, "busy yesterday", "."],
        explanation: "주어가 복수 <b>They</b> → 과거형은 <code>were</code>.",
      },
      {
        id: "e1",
        type: "error",
        ko: "나는 학생이 아니다.",
        tokens: ["I", "are", "not", "a", "student", "."],
        wrongIndex: 1,
        fix: "am",
        explanation: "주어가 <b>I</b>일 때 be동사는 언제나 <code>am</code>.",
      },
      {
        id: "e2",
        type: "error",
        ko: "그 책들은 탁자 위에 있다.",
        tokens: ["The", "books", "is", "on", "the", "table", "."],
        wrongIndex: 2,
        fix: "are",
        explanation: "<b>books</b>는 복수 명사 → <code>are</code>.",
      },
    ],
  },

  {
    id: "do-aff",
    title: "일반동사 긍정",
    kind: "basic",
    blurb: "동사원형 / 3인칭 단수 -s",
    summary: [
      { t: "h", text: "일반동사 = be동사가 아닌 모든 동사" },
      { t: "p", text: "예: <code>like, play, eat, study, run, want</code> ..." },
      { t: "h", text: "주어에 따른 형태" },
      {
        t: "table",
        head: ["주어", "동사 형태", "예시"],
        rows: [
          ["I / You / We / They", "<b>원형</b>", "I <code>like</code> apples."],
          ["He / She / It (3인칭 단수)", "<b>-s / -es</b>", "He <code>likes</code> apples."],
        ],
      },
      { t: "h", text: "-s / -es 붙이는 규칙" },
      { t: "p", text: "• 대부분: <code>+s</code> (likes, plays)<br> • -o, -s, -ss, -ch, -sh, -x로 끝나면: <code>+es</code> (goes, watches)<br> • 자음+y: y → i + es (study → studies)" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 사과를 좋아한다.",
        prefix: ["I"],
        answer: ["like"],
        suffix: ["apples", "."],
        distractors: ["likes", "am", "do"],
        explanation: "<b>I</b>는 동사 원형 → <code>like</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 매일 영어를 공부한다.",
        prefix: ["She"],
        answer: ["studies"],
        suffix: ["English", "every", "day", "."],
        distractors: ["study", "studys", "studied"],
        explanation: "<b>she</b>는 3인칭 단수 → 자음+y는 y→i+es → <code>studies</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그는 학교에 간다.",
        prefix: ["He"],
        answer: ["goes"],
        suffix: ["to", "school", "."],
        distractors: ["go", "gos", "going"],
        explanation: "<b>go</b>는 -o로 끝나므로 <code>+es</code> → <code>goes</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "우리는 축구를 한다.",
        prefix: ["We"],
        answer: ["play"],
        suffix: ["soccer", "."],
        distractors: ["plays", "playing", "played"],
        explanation: "<b>We</b>는 원형 → <code>play</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "Tom은 TV를 본다.",
        prefix: ["Tom"],
        answer: ["watches"],
        suffix: ["TV", "."],
        distractors: ["watch", "watchs", "watched"],
        explanation: "<b>Tom</b>은 3인칭 단수. <code>watch</code>는 -ch로 끝나므로 <code>+es</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그들은 한국어를 한다.",
        prefix: ["They"],
        answer: ["speak"],
        suffix: ["Korean", "."],
        distractors: ["speaks", "spoke", "speaking"],
        explanation: "<b>They</b>는 복수 → 원형 <code>speak</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "내 고양이는 우유를 마신다.",
        prefix: ["My", "cat"],
        answer: ["drinks"],
        suffix: ["milk", "."],
        distractors: ["drink", "drinked", "drank"],
        explanation: "<b>cat</b>은 3인칭 단수 → <code>drinks</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "나는 너를 안다.",
        prefix: ["I"],
        answer: ["know"],
        suffix: ["you", "."],
        distractors: ["knows", "knew", "am"],
        explanation: "<b>I</b> → 원형 <code>know</code>.",
      },
    ],
  },

  {
    id: "do-neg",
    title: "일반동사 부정",
    kind: "basic",
    blurb: "don't / doesn't + 동사원형",
    summary: [
      { t: "h", text: "일반동사 부정문" },
      { t: "p", text: "be동사와 달리, 일반동사 부정에는 <b>do/does + not</b>이라는 <u>도우미</u>가 필요해요." },
      {
        t: "table",
        head: ["주어", "부정 표현", "본동사"],
        rows: [
          ["I / You / We / They", "<code>do not (don't)</code>", "+ 동사원형"],
          ["He / She / It", "<code>does not (doesn't)</code>", "+ 동사원형"],
        ],
      },
      { t: "p", text: "⚠️ <code>doesn't</code> 뒤에는 동사 원형! <b>likes</b>가 아니라 <b>like</b>입니다." },
      { t: "p", text: "예: She <b>doesn't like</b> coffee. (○) / She doesn't <s>likes</s> coffee. (✗)" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 커피를 마시지 않는다.",
        prefix: ["I"],
        answer: ["don't", "drink"],
        suffix: ["coffee", "."],
        distractors: ["doesn't", "am not", "drinks", "drank"],
        explanation: "<b>I</b> → <code>don't + 원형</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그는 영어를 공부하지 않는다.",
        prefix: ["He"],
        answer: ["doesn't", "study"],
        suffix: ["English", "."],
        distractors: ["don't", "isn't", "studies", "studied"],
        explanation: "<b>He</b>는 3인칭 단수 → <code>doesn't</code>. 뒤에는 원형 <code>study</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "우리는 고기를 먹지 않는다.",
        prefix: ["We"],
        answer: ["don't", "eat"],
        suffix: ["meat", "."],
        distractors: ["doesn't", "aren't", "eats", "ate"],
        explanation: "<b>We</b>는 복수 → <code>don't + 원형</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그녀는 그를 모른다.",
        prefix: ["She"],
        answer: ["doesn't", "know"],
        suffix: ["him", "."],
        distractors: ["don't", "isn't", "knows", "knew"],
        explanation: "<b>She</b> → <code>doesn't</code> + 원형 <code>know</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그들은 한국에 살지 않는다.",
        prefix: ["They"],
        answer: ["don't", "live"],
        suffix: ["in", "Korea", "."],
        distractors: ["doesn't", "aren't", "lives", "lived"],
        explanation: "<b>They</b> → <code>don't + 원형</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "내 동생은 채소를 좋아하지 않는다.",
        prefix: ["My", "brother"],
        answer: ["doesn't", "like"],
        suffix: ["vegetables", "."],
        distractors: ["don't", "isn't", "likes", "liked"],
        explanation: "<b>brother</b>는 3인칭 단수 → <code>doesn't + 원형</code>.",
      },
    ],
  },

  {
    id: "do-q",
    title: "일반동사 의문",
    kind: "basic",
    blurb: "Do / Does + 주어 + 동사원형 ?",
    summary: [
      { t: "h", text: "일반동사 의문문" },
      { t: "p", text: "문장 맨 앞에 <b>Do</b> 또는 <b>Does</b>를 둡니다. 본동사는 항상 <b>원형</b>!" },
      {
        t: "table",
        head: ["주어", "의문문"],
        rows: [
          ["I / You / We / They", "<code>Do</code> + 주어 + 원형 ~?"],
          ["He / She / It", "<code>Does</code> + 주어 + 원형 ~?"],
        ],
      },
      { t: "p", text: "예: <b>Do</b> you <code>like</code> pizza? / <b>Does</b> he <code>play</code> tennis?" },
      { t: "p", text: "⚠️ <code>Does she likes ...?</code> (✗) → <code>Does she like ...?</code> (○)" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "너는 피자를 좋아하니?",
        answer: ["Do"],
        suffix: ["you", "like", "pizza", "?"],
        distractors: ["Does", "Are", "Is", "Am"],
        explanation: "<b>you</b> → <code>Do</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그는 영어를 가르치니?",
        answer: ["Does"],
        suffix: ["he", "teach", "English", "?"],
        distractors: ["Do", "Is", "Are", "Am"],
        explanation: "<b>he</b>는 3인칭 단수 → <code>Does</code>. 뒤는 원형 <code>teach</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그들은 함께 사니?",
        answer: ["Do"],
        suffix: ["they", "live", "together", "?"],
        distractors: ["Does", "Are", "Is", "Am"],
        explanation: "<b>they</b> → <code>Do</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그녀는 한국어를 하니?",
        answer: ["Does"],
        suffix: ["she", "speak", "Korean", "?"],
        distractors: ["Do", "Is", "Are", "Am"],
        explanation: "<b>she</b> → <code>Does</code> + 원형 <code>speak</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "너희는 매일 운동하니?",
        answer: ["Do"],
        suffix: ["you", "exercise", "every", "day", "?"],
        distractors: ["Does", "Are", "Is", "Am"],
        explanation: "<b>you</b>(복수도 가능) → <code>Do</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "이 가게는 일요일에 여나요?",
        answer: ["Does"],
        suffix: ["this", "store", "open", "on", "Sundays", "?"],
        distractors: ["Do", "Are", "Is", "Am"],
        explanation: "<b>this store</b>는 단수 → <code>Does</code>.",
      },
    ],
  },

  {
    id: "do-negq",
    title: "일반동사 부정의문",
    kind: "basic",
    blurb: "Don't / Doesn't + 주어 ~?",
    summary: [
      { t: "h", text: "일반동사 부정의문문" },
      { t: "p", text: "\"~하지 않니?\"라고 묻는 형태. 줄임말을 문장 맨 앞에 둡니다." },
      { t: "p", text: "어순: <code>Don't / Doesn't + 주어 + 동사원형 ~?</code>" },
      {
        t: "table",
        head: ["긍정의문", "부정의문"],
        rows: [
          ["Do you know?", "<b>Don't</b> you know?"],
          ["Does he like it?", "<b>Doesn't</b> he like it?"],
        ],
      },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "너 그거 모르니?",
        answer: ["Don't"],
        suffix: ["you", "know", "that", "?"],
        distractors: ["Doesn't", "Aren't", "Isn't", "Not"],
        explanation: "<b>you</b> → <code>Don't</code> + 원형.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 너를 좋아하지 않니?",
        answer: ["Doesn't"],
        suffix: ["she", "like", "you", "?"],
        distractors: ["Don't", "Aren't", "Isn't", "Not"],
        explanation: "<b>she</b> → <code>Doesn't</code> + 원형 <code>like</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그들은 영어 안 하니?",
        answer: ["Don't"],
        suffix: ["they", "speak", "English", "?"],
        distractors: ["Doesn't", "Aren't", "Isn't", "Not"],
        explanation: "<b>they</b> → <code>Don't</code> + 원형.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "Tom은 채소 안 먹니?",
        answer: ["Doesn't"],
        suffix: ["Tom", "eat", "vegetables", "?"],
        distractors: ["Don't", "Aren't", "Isn't", "Not"],
        explanation: "<b>Tom</b>은 3인칭 단수 → <code>Doesn't</code> + 원형 <code>eat</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "너희 같이 안 가니?",
        answer: ["Don't"],
        suffix: ["you", "go", "together", "?"],
        distractors: ["Doesn't", "Aren't", "Isn't", "Not"],
        explanation: "<b>you</b> → <code>Don't</code> + 원형.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "이 버스는 시청에 안 가나요?",
        answer: ["Doesn't"],
        suffix: ["this", "bus", "go", "to", "City", "Hall", "?"],
        distractors: ["Don't", "Aren't", "Isn't", "Not"],
        explanation: "<b>this bus</b>(단수) → <code>Doesn't</code> + 원형 <code>go</code>.",
      },
    ],
  },

  {
    id: "do-review",
    title: "일반동사 통합 정리",
    kind: "review",
    blurb: "긍정·부정·의문·부정의문 한꺼번에",
    summary: [
      { t: "h", text: "일반동사 4가지 형태 한눈에 (3인칭 단수 주어 기준)" },
      {
        t: "table",
        head: ["형태", "어순", "예시 (He / play)"],
        rows: [
          ["긍정", "주어 + 동사-s", "He <b>plays</b>."],
          ["부정", "주어 + doesn't + 원형", "He <b>doesn't play</b>."],
          ["의문", "Does + 주어 + 원형 ?", "<b>Does</b> he <b>play</b>?"],
          ["부정의문", "Doesn't + 주어 + 원형 ?", "<b>Doesn't</b> he <b>play</b>?"],
        ],
      },
      { t: "p", text: "💡 핵심: <b>does가 나오면 본동사는 무조건 원형!</b>" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그는 매일 책을 읽는다.",
        prefix: ["He"],
        answer: ["reads"],
        suffix: ["books", "every", "day", "."],
        distractors: ["read", "is reading", "doesn't read"],
        explanation: "긍정 + 3인칭 단수 → <code>reads</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "나는 그것을 좋아하지 않는다.",
        prefix: ["I"],
        answer: ["don't", "like"],
        suffix: ["it", "."],
        distractors: ["doesn't", "am not", "likes", "liked"],
        explanation: "부정 + I → <code>don't + 원형</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그녀는 한국어를 하니?",
        answer: ["Does"],
        suffix: ["she", "speak", "Korean", "?"],
        distractors: ["Do", "Is", "Are"],
        explanation: "의문 + she → <code>Does</code> + 원형.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "너 그거 안 좋아하니?",
        answer: ["Don't"],
        suffix: ["you", "like", "it", "?"],
        distractors: ["Doesn't", "Aren't", "Isn't"],
        explanation: "부정의문 + you → <code>Don't</code> + 원형.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그들은 영어를 가르치지 않는다.",
        prefix: ["They"],
        answer: ["don't teach"],
        suffix: ["English", "."],
        distractors: ["doesn't teach", "don't teaches", "aren't teaching", "not teach"],
        explanation: "부정 + they → <code>don't + 원형 teach</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "내 형은 운동을 한다.",
        prefix: ["My", "brother"],
        answer: ["exercises"],
        suffix: ["."],
        distractors: ["exercise", "is exercising", "doesn't"],
        explanation: "<b>brother</b>는 3인칭 단수 → <code>exercises</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그는 너를 모르니?",
        answer: ["Doesn't"],
        suffix: ["he", "know", "you", "?"],
        distractors: ["Don't", "Isn't", "Aren't"],
        explanation: "부정의문 + he → <code>Doesn't</code> + 원형 <code>know</code>.",
      },
      {
        id: "c1",
        type: "choice",
        ko: "그는 매일 축구를 한다.",
        choices: ["play", "plays"],
        correct: 1,
        sentence: ["He", null, "soccer every day", "."],
        explanation: "3인칭 단수 현재 → 동사에 <code>-s</code>.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "너는 커피를 좋아하니?",
        choices: ["Do", "Does"],
        correct: 0,
        sentence: [null, "you like coffee", "?"],
        explanation: "주어가 <b>you</b> → <code>Do</code>로 묻는다.",
      },
      {
        id: "e1",
        type: "error",
        ko: "그녀는 생선을 좋아하지 않는다.",
        tokens: ["She", "don't", "like", "fish", "."],
        wrongIndex: 1,
        fix: "doesn't",
        explanation: "3인칭 단수 부정 → <code>doesn't</code>.",
      },
      {
        id: "e2",
        type: "error",
        ko: "그는 학교에 가니?",
        tokens: ["Does", "he", "goes", "to", "school", "?"],
        wrongIndex: 2,
        fix: "go",
        explanation: "<code>Does</code>가 이미 3인칭 단수를 나타내므로 본동사는 원형.",
      },
    ],
  },

  {
    id: "present-mega",
    title: "현재시제 대왕 정리",
    kind: "mega",
    blurb: "be동사 vs 일반동사 — 한 챕터에서 끝내기",
    summary: [
      { t: "h", text: "be동사 vs 일반동사 — 가장 큰 차이" },
      {
        t: "table",
        head: ["", "be동사", "일반동사"],
        rows: [
          ["부정", "be + <b>not</b>", "<b>don't/doesn't</b> + 원형"],
          ["의문", "be를 주어 앞으로", "맨 앞에 <b>Do/Does</b>"],
        ],
      },
      { t: "p", text: "💡 한 문장 안에 <b>두 가지를 섞으면 안 돼요</b>: <s>Is he plays?</s> → <code>Does he play?</code>" },
      { t: "h", text: "주어별 매칭 표" },
      {
        t: "table",
        head: ["주어", "be", "일반동사", "do"],
        rows: [
          ["I", "am", "원형", "do"],
          ["You / We / They / 복수", "are", "원형", "do"],
          ["He / She / It / 단수", "is", "-s/-es", "does"],
        ],
      },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그녀는 매일 영어를 공부한다.",
        prefix: ["She"],
        answer: ["studies"],
        suffix: ["English", "every", "day", "."],
        distractors: ["is", "study", "is studying", "doesn't study"],
        explanation: "긍정 일반동사 + 3인칭 단수 → <code>studies</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그는 학생이 아니다.",
        prefix: ["He"],
        answer: ["is", "not"],
        suffix: ["a", "student", "."],
        distractors: ["doesn't", "isn't be", "are not", "don't"],
        explanation: "be동사 부정 → <code>is not</code>. (일반동사 아닌 명사 보충어이므로 be 사용)",
      },
      {
        id: "q3",
        type: "blank",
        ko: "너 일찍 일어나니?",
        answer: ["Do"],
        suffix: ["you", "get", "up", "early", "?"],
        distractors: ["Are", "Is", "Does"],
        explanation: "일반동사 의문 + you → <code>Do</code>. (<code>get up</code>은 일반동사)",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그들은 바쁘지 않니?",
        answer: ["Aren't"],
        suffix: ["they", "busy", "?"],
        distractors: ["Don't", "Isn't", "Doesn't"],
        explanation: "busy는 형용사 → be동사 + not의 부정의문 → <code>Aren't</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "내 부모님은 나를 사랑하신다.",
        prefix: ["My", "parents"],
        answer: ["love"],
        suffix: ["me", "."],
        distractors: ["loves", "are", "is loving"],
        explanation: "<b>parents</b>는 복수 → 원형 <code>love</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그것은 비싸지 않다.",
        prefix: ["It"],
        answer: ["is", "not"],
        suffix: ["expensive", "."],
        distractors: ["doesn't", "isn't be", "don't", "aren't"],
        explanation: "형용사 보충어 → be동사 부정 <code>is not</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "Tom은 채소를 안 먹는다.",
        prefix: ["Tom"],
        answer: ["doesn't", "eat"],
        suffix: ["vegetables", "."],
        distractors: ["don't", "isn't", "eats", "is not"],
        explanation: "일반동사 <code>eat</code> + 3인칭 단수 부정 → <code>doesn't eat</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "이 책 재미있지 않니?",
        answer: ["Isn't"],
        suffix: ["this", "book", "interesting", "?"],
        distractors: ["Doesn't", "Don't", "Aren't"],
        explanation: "interesting은 형용사 → be동사 부정의문 <code>Isn't</code>.",
      },
      {
        id: "c1",
        type: "choice",
        ko: "내 여동생은 피아노를 치지 않는다.",
        choices: ["don't", "doesn't"],
        correct: 1,
        sentence: ["My sister", null, "play the piano", "."],
        explanation: "<b>My sister</b>는 3인칭 단수 → <code>doesn't</code>.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "그들은 지금 행복하다.",
        choices: ["is", "are"],
        correct: 1,
        sentence: ["They", null, "happy now", "."],
        explanation: "복수 주어 <b>They</b> → <code>are</code>.",
      },
      {
        id: "e1",
        type: "error",
        ko: "Tom은 새 자전거를 가지고 있다.",
        tokens: ["Tom", "have", "a", "new", "bike", "."],
        wrongIndex: 1,
        fix: "has",
        explanation: "3인칭 단수 주어의 have → <code>has</code>.",
      },
      {
        id: "e2",
        type: "error",
        ko: "그녀는 영어를 공부하니?",
        tokens: ["Do", "she", "study", "English", "?"],
        wrongIndex: 0,
        fix: "Does",
        explanation: "주어가 3인칭 단수 <b>she</b> → <code>Does</code>.",
      },
    ],
  },

  {
    id: "be-past",
    title: "be동사 과거",
    kind: "basic",
    blurb: "was / were",
    summary: [
      { t: "h", text: "be동사 과거형" },
      {
        t: "table",
        head: ["주어", "현재", "과거"],
        rows: [
          ["I / He / She / It / 단수", "am / is", "<b>was</b>"],
          ["You / We / They / 복수", "are", "<b>were</b>"],
        ],
      },
      { t: "p", text: "부정: <code>was not (wasn't) / were not (weren't)</code><br> 의문: <code>Was/Were + 주어 ~?</code>" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 어제 바빴다.",
        prefix: ["I"],
        answer: ["was"],
        suffix: ["busy", "yesterday", "."],
        distractors: ["were", "is", "am"],
        explanation: "<b>I</b>의 과거 → <code>was</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그들은 학교에 있었다.",
        prefix: ["They"],
        answer: ["were"],
        suffix: ["at", "school", "."],
        distractors: ["was", "are", "is"],
        explanation: "<b>They</b>는 복수 → <code>were</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그는 행복하지 않았다.",
        prefix: ["He"],
        answer: ["wasn't"],
        suffix: ["happy", "."],
        distractors: ["weren't", "isn't", "didn't"],
        explanation: "<b>He</b> 과거 부정 → <code>wasn't</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "너는 거기 있었니?",
        answer: ["Were"],
        suffix: ["you", "there", "?"],
        distractors: ["Was", "Did", "Are"],
        explanation: "<b>you</b> → <code>Were</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그것은 쉬웠다.",
        prefix: ["It"],
        answer: ["was"],
        suffix: ["easy", "."],
        distractors: ["were", "is", "did"],
        explanation: "<b>It</b>은 단수 → <code>was</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "우리는 늦지 않았다.",
        prefix: ["We"],
        answer: ["weren't"],
        suffix: ["late", "."],
        distractors: ["wasn't", "aren't", "didn't"],
        explanation: "<b>We</b>는 복수 → <code>weren't</code>.",
      },
    ],
  },

  {
    id: "do-past",
    title: "일반동사 과거",
    kind: "basic",
    blurb: "동사 + -ed / 불규칙 변화",
    summary: [
      { t: "h", text: "일반동사 과거형" },
      { t: "p", text: "대부분 동사 끝에 <code>-ed</code>를 붙입니다. 단, <b>불규칙 동사</b>는 따로 외워야 해요." },
      { t: "h", text: "-ed 규칙" },
      { t: "p", text: "• 대부분: <code>+ed</code> (played, worked)<br> • -e로 끝남: <code>+d</code> (liked, lived)<br> • 자음+y: y→i+ed (studied, tried)" },
      { t: "h", text: "자주 쓰는 불규칙" },
      {
        t: "table",
        rows: [
          ["go → <b>went</b>", "eat → <b>ate</b>", "see → <b>saw</b>"],
          ["have → <b>had</b>", "do → <b>did</b>", "come → <b>came</b>"],
          ["buy → <b>bought</b>", "get → <b>got</b>", "make → <b>made</b>"],
        ],
      },
      { t: "h", text: "부정 / 의문" },
      { t: "p", text: "부정: <code>didn't + 원형</code><br> 의문: <code>Did + 주어 + 원형 ?</code>" },
      { t: "p", text: "⚠️ <b>did</b>가 나오면 본동사는 항상 <b>원형</b>! → <s>Did you went?</s> → <code>Did you go?</code>" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 어제 축구를 했다.",
        prefix: ["I"],
        answer: ["played"],
        suffix: ["soccer", "yesterday", "."],
        distractors: ["play", "plays", "did play"],
        explanation: "<code>play</code>의 과거 → <code>played</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그는 어제 학교에 갔다.",
        prefix: ["He"],
        answer: ["went"],
        suffix: ["to", "school", "yesterday", "."],
        distractors: ["goes", "go", "goed"],
        explanation: "<code>go</code>는 불규칙 → 과거 <code>went</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그녀는 영어를 공부했다.",
        prefix: ["She"],
        answer: ["studied"],
        suffix: ["English", "."],
        distractors: ["studyed", "study", "studies"],
        explanation: "자음+y → y를 i로 + ed → <code>studied</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "우리는 그것을 안 봤다.",
        prefix: ["We"],
        answer: ["didn't", "see"],
        suffix: ["it", "."],
        distractors: ["don't", "didn't saw", "weren't", "saw not"],
        explanation: "과거 부정: <code>didn't + 원형 see</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "너 어제 그를 만났니?",
        answer: ["Did"],
        suffix: ["you", "meet", "him", "yesterday", "?"],
        distractors: ["Do", "Were", "Was"],
        explanation: "과거 의문: <code>Did + 주어 + 원형</code>. 본동사는 <code>meet</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그는 그 책을 안 샀다.",
        prefix: ["He"],
        answer: ["didn't", "buy"],
        suffix: ["the", "book", "."],
        distractors: ["doesn't", "didn't bought", "wasn't", "bought not"],
        explanation: "<code>didn't</code> 뒤는 원형 <code>buy</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그들은 점심을 먹었다.",
        prefix: ["They"],
        answer: ["ate"],
        suffix: ["lunch", "."],
        distractors: ["eat", "eated", "eats"],
        explanation: "<code>eat</code> 불규칙 → 과거 <code>ate</code>.",
      },
    ],
  },

  {
    id: "past-review",
    title: "과거시제 정리",
    kind: "review",
    blurb: "was/were vs did + 원형",
    summary: [
      { t: "h", text: "과거시제 — be vs 일반동사" },
      {
        t: "table",
        head: ["", "be동사 (was/were)", "일반동사 (did)"],
        rows: [
          ["긍정", "주어 + was/were + 형용사/명사", "주어 + 동사과거"],
          ["부정", "was/were + not", "didn't + <b>원형</b>"],
          ["의문", "Was/Were + 주어 ~?", "Did + 주어 + <b>원형</b> ~?"],
        ],
      },
      { t: "p", text: "💡 <code>did</code>가 나오면 일반동사는 항상 <b>원형</b>!" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그는 어제 아팠다.",
        prefix: ["He"],
        answer: ["was"],
        suffix: ["sick", "yesterday", "."],
        distractors: ["were", "did", "was being"],
        explanation: "형용사 → be동사 과거 <code>was</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "우리는 그 영화를 봤다.",
        prefix: ["We"],
        answer: ["saw"],
        suffix: ["the", "movie", "."],
        distractors: ["seen", "see", "did saw", "were seen"],
        explanation: "<code>see</code>의 불규칙 과거 → <code>saw</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "너 어제 도서관에 갔니?",
        answer: ["Did"],
        suffix: ["you", "go", "to", "the", "library", "?"],
        distractors: ["Were", "Was", "Do"],
        explanation: "일반동사 의문 과거 → <code>Did</code> + 원형 <code>go</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그들은 행복하지 않았다.",
        prefix: ["They"],
        answer: ["weren't"],
        suffix: ["happy", "."],
        distractors: ["wasn't", "didn't", "aren't"],
        explanation: "복수 + be 과거 부정 → <code>weren't</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그녀는 점심을 안 먹었다.",
        prefix: ["She"],
        answer: ["didn't", "eat"],
        suffix: ["lunch", "."],
        distractors: ["wasn't", "didn't ate", "ate not", "doesn't"],
        explanation: "일반동사 과거 부정 → <code>didn't + 원형 eat</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그것 어려웠니?",
        answer: ["Was"],
        suffix: ["it", "difficult", "?"],
        distractors: ["Did", "Were", "Does"],
        explanation: "형용사 보충어 → <code>Was it ...?</code>",
      },
      {
        id: "c1",
        type: "choice",
        ko: "우리는 어제 영화를 봤다.",
        choices: ["watch", "watched"],
        correct: 1,
        sentence: ["We", null, "a movie yesterday", "."],
        explanation: "<b>yesterday</b>가 있으니 과거형 <code>watched</code>.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "그는 그때 집에 없었다.",
        choices: ["wasn't", "weren't"],
        correct: 0,
        sentence: ["He", null, "at home then", "."],
        explanation: "단수 주어 <b>He</b>의 과거 부정 → <code>wasn't</code>.",
      },
      {
        id: "e1",
        type: "error",
        ko: "나는 공원에 갔다.",
        tokens: ["I", "goed", "to", "the", "park", "."],
        wrongIndex: 1,
        fix: "went",
        explanation: "<b>go</b>는 불규칙 동사 — 과거형은 <code>went</code>.",
      },
      {
        id: "e2",
        type: "error",
        ko: "너는 그를 봤니?",
        tokens: ["Did", "you", "saw", "him", "?"],
        wrongIndex: 2,
        fix: "see",
        explanation: "<code>Did</code>가 과거를 나타내므로 본동사는 원형 <code>see</code>.",
      },
    ],
  },

  {
    id: "be-future",
    title: "be동사 미래",
    kind: "basic",
    blurb: "will be / be going to be",
    summary: [
      { t: "h", text: "be동사 미래형" },
      { t: "p", text: "주어와 상관없이 <b>will + be</b>, 또는 <b>be going to + be</b>를 씁니다." },
      {
        t: "table",
        head: ["형태", "예시"],
        rows: [
          ["긍정", "I <code>will be</code> there. / I'<code>m going to be</code> there."],
          ["부정", "I <code>won't be</code> there."],
          ["의문", "<code>Will</code> you <code>be</code> there?"],
        ],
      },
      { t: "p", text: "⚠️ <code>will</code> 뒤에는 <b>주어와 상관없이 항상 be 원형</b>! (will <s>is</s> → will be)" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 내일 바쁠 것이다.",
        prefix: ["I"],
        answer: ["will", "be"],
        suffix: ["busy", "tomorrow", "."],
        distractors: ["am", "will is", "willing", "be will"],
        explanation: "<code>will + be</code> (주어 무관).",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 의사가 될 것이다.",
        prefix: ["She"],
        answer: ["will be"],
        suffix: ["a", "doctor", "."],
        distractors: ["is", "will is", "would", "be"],
        explanation: "<code>will + be</code>. <b>She</b>여도 <code>will is</code>가 아닙니다.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그들은 늦지 않을 것이다.",
        prefix: ["They"],
        answer: ["won't", "be"],
        suffix: ["late", "."],
        distractors: ["aren't", "willn't", "don't be", "won't is"],
        explanation: "<code>will not = won't</code>. 뒤는 <code>be</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "너는 학교에 있을 거니?",
        answer: ["Will"],
        suffix: ["you", "be", "at", "school", "?"],
        distractors: ["Are", "Do", "Is"],
        explanation: "<code>Will + 주어 + be</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "오늘 날씨가 추울 것이다.",
        prefix: ["It"],
        answer: ["will be"],
        suffix: ["cold", "today", "."],
        distractors: ["is", "would", "will is", "be"],
        explanation: "날씨도 <code>It will be ...</code>.",
      },
    ],
  },

  {
    id: "do-future",
    title: "일반동사 미래",
    kind: "basic",
    blurb: "will + 동사원형",
    summary: [
      { t: "h", text: "일반동사 미래형" },
      { t: "p", text: "주어와 상관없이 <b>will + 동사원형</b>." },
      { t: "p", text: "또는 <b>be going to + 동사원형</b>도 같은 의미 (예정·계획)." },
      {
        t: "table",
        head: ["형태", "예시"],
        rows: [
          ["긍정", "I <code>will go</code>. / I'<code>m going to go</code>."],
          ["부정", "I <code>won't go</code>."],
          ["의문", "<code>Will</code> you <code>go</code>?"],
        ],
      },
      { t: "p", text: "⚠️ <code>will</code> 뒤는 <b>항상 동사 원형</b>! → <s>will goes</s>, <s>will went</s> 모두 ✗" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 내일 너를 만날 것이다.",
        prefix: ["I"],
        answer: ["will", "meet"],
        suffix: ["you", "tomorrow", "."],
        distractors: ["am", "will met", "meet will", "meets"],
        explanation: "<code>will + 원형 meet</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그는 너에게 전화할 것이다.",
        prefix: ["He"],
        answer: ["will", "call"],
        suffix: ["you", "."],
        distractors: ["calls", "will calls", "is calling", "called"],
        explanation: "<code>will + 원형 call</code>. (주어가 He여도 calls가 아님!)",
      },
      {
        id: "q3",
        type: "blank",
        ko: "우리는 그 영화를 안 볼 것이다.",
        prefix: ["We"],
        answer: ["won't", "watch"],
        suffix: ["the", "movie", "."],
        distractors: ["don't", "willn't", "won't watched", "aren't"],
        explanation: "<code>will not = won't</code> + 원형 <code>watch</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "너는 나를 도와줄 거니?",
        answer: ["Will"],
        suffix: ["you", "help", "me", "?"],
        distractors: ["Do", "Are", "Did"],
        explanation: "<code>Will + 주어 + 원형</code>. 본동사는 <code>help</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그녀는 곧 도착할 것이다.",
        prefix: ["She"],
        answer: ["will", "arrive"],
        suffix: ["soon", "."],
        distractors: ["arrives", "will arrives", "is arriving", "arrived"],
        explanation: "<code>will + 원형 arrive</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그들은 안 올 것이다.",
        prefix: ["They"],
        answer: ["won't", "come"],
        suffix: ["."],
        distractors: ["don't", "aren't", "willn't", "won't came"],
        explanation: "<code>won't + 원형 come</code>.",
      },
    ],
  },

  {
    id: "future-review",
    title: "미래시제 정리",
    kind: "review",
    blurb: "will + 원형 — be든 일반이든 항상 원형",
    summary: [
      { t: "h", text: "미래시제 — 단 하나의 규칙" },
      { t: "p", text: "<b>will 뒤에는 무조건 동사 원형!</b>" },
      {
        t: "table",
        head: ["형태", "be동사", "일반동사"],
        rows: [
          ["긍정", "will <b>be</b>", "will + <b>원형</b>"],
          ["부정", "won't <b>be</b>", "won't + <b>원형</b>"],
          ["의문", "Will ... <b>be</b> ?", "Will ... <b>원형</b> ?"],
        ],
      },
      { t: "p", text: "💡 주어가 he/she여도 <code>will is</code>, <code>will plays</code> 같은 건 없어요." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그는 내일 여기에 있을 것이다.",
        prefix: ["He"],
        answer: ["will be"],
        suffix: ["here", "tomorrow", "."],
        distractors: ["is", "will is", "would", "be"],
        explanation: "be동사 미래 → <code>will be</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 안 올 것이다.",
        prefix: ["She"],
        answer: ["won't", "come"],
        suffix: ["."],
        distractors: ["doesn't", "willn't", "won't came", "isn't"],
        explanation: "일반동사 미래 부정 → <code>won't + 원형 come</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "너는 행복할 거니?",
        answer: ["Will"],
        suffix: ["you", "be", "happy", "?"],
        distractors: ["Are", "Do", "Were"],
        explanation: "be동사 미래 의문 → <code>Will + 주어 + be ...?</code>",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그들이 우리를 도와줄 것이다.",
        prefix: ["They"],
        answer: ["will help"],
        suffix: ["us", "."],
        distractors: ["help", "are helping", "will helps", "helped"],
        explanation: "<code>will + 원형 help</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "내일 비가 올 것이다.",
        prefix: ["It"],
        answer: ["will", "rain"],
        suffix: ["tomorrow", "."],
        distractors: ["rains", "is raining", "will rains", "rained"],
        explanation: "It + <code>will + 원형 rain</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그는 늦지 않을 거니?",
        answer: ["Won't"],
        suffix: ["he", "be", "late", "?"],
        distractors: ["Doesn't", "Isn't", "Don't"],
        explanation: "미래 부정의문 → <code>Won't + 주어 + be ...?</code>",
      },
      {
        id: "c1",
        type: "choice",
        ko: "나는 내일 그를 만날 것이다.",
        choices: ["meet", "to meet"],
        correct: 0,
        sentence: ["I will", null, "him tomorrow", "."],
        explanation: "조동사 <code>will</code> 뒤에는 동사원형.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "그녀는 곧 도착할 것이다.",
        choices: ["is going to", "is going"],
        correct: 0,
        sentence: ["She", null, "arrive soon", "."],
        explanation: "<code>be going to + 동사원형</code>.",
      },
      {
        id: "e1",
        type: "error",
        ko: "그는 서울에 갈 것이다.",
        tokens: ["He", "will", "goes", "to", "Seoul", "."],
        wrongIndex: 2,
        fix: "go",
        explanation: "<code>will</code> 뒤에는 언제나 동사원형.",
      },
      {
        id: "e2",
        type: "error",
        ko: "내일은 비가 올 것이다.",
        tokens: ["It", "will", "is", "rainy", "tomorrow", "."],
        wrongIndex: 2,
        fix: "be",
        explanation: "<code>will</code> 뒤의 be동사는 원형 <code>be</code>.",
      },
    ],
  },

  {
    id: "all-mega",
    title: "현재·과거·미래 대왕 정리",
    kind: "mega",
    blurb: "세 시제를 한 챕터에서 마스터하기",
    summary: [
      { t: "h", text: "한눈에 보는 시제 표" },
      {
        t: "table",
        head: ["", "현재", "과거", "미래"],
        rows: [
          ["be동사", "am/are/is", "was/were", "will be"],
          ["일반동사", "원형 / -s", "-ed / 불규칙", "will + 원형"],
          ["일반동사 부정", "don't/doesn't + 원형", "didn't + 원형", "won't + 원형"],
          ["일반동사 의문", "Do/Does + 원형?", "Did + 원형?", "Will + 원형?"],
        ],
      },
      { t: "h", text: "핵심 한 줄 요약" },
      { t: "p", text: "1) be동사는 자기가 직접 변신 (am/is/are → was/were → will be).<br> 2) 일반동사는 도우미(do/does/did/will) + 본동사. <b>도우미가 있으면 본동사는 원형</b>." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 어제 바빴다.",
        prefix: ["I"],
        answer: ["was"],
        suffix: ["busy", "yesterday", "."],
        distractors: ["am", "were", "will be", "did"],
        explanation: "과거 + I → <code>was</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 내일 학교에 갈 것이다.",
        prefix: ["She"],
        answer: ["will", "go"],
        suffix: ["to", "school", "tomorrow", "."],
        distractors: ["goes", "went", "will goes", "is going"],
        explanation: "미래 일반동사 → <code>will + 원형 go</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그는 매일 영어를 공부한다.",
        prefix: ["He"],
        answer: ["studies"],
        suffix: ["English", "every", "day", "."],
        distractors: ["study", "studied", "will study", "is study"],
        explanation: "현재 일반동사 + 3인칭 단수 → <code>studies</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그들은 어제 안 왔다.",
        prefix: ["They"],
        answer: ["didn't", "come"],
        suffix: ["yesterday", "."],
        distractors: ["don't", "won't", "didn't came", "weren't"],
        explanation: "과거 일반동사 부정 → <code>didn't + 원형 come</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "너 지금 행복하니?",
        answer: ["Are"],
        suffix: ["you", "happy", "now", "?"],
        distractors: ["Do", "Did", "Were", "Will"],
        explanation: "현재 + 형용사 → be동사 의문 <code>Are</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "내일 비가 안 올 것이다.",
        prefix: ["It"],
        answer: ["won't", "rain"],
        suffix: ["tomorrow", "."],
        distractors: ["doesn't", "didn't", "won't rained", "isn't"],
        explanation: "미래 부정 → <code>won't + 원형 rain</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "너 어제 그를 봤니?",
        answer: ["Did"],
        suffix: ["you", "see", "him", "yesterday", "?"],
        distractors: ["Do", "Were", "Will", "Was"],
        explanation: "과거 일반동사 의문 → <code>Did + 주어 + 원형 see</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "우리는 한국 출신이다.",
        prefix: ["We"],
        answer: ["are"],
        suffix: ["from", "Korea", "."],
        distractors: ["am", "is", "were", "will be"],
        explanation: "현재 + 복수 → <code>are</code>.",
      },
      {
        id: "c1",
        type: "choice",
        ko: "그는 작년에 부산에 살았다.",
        choices: ["lives", "lived"],
        correct: 1,
        sentence: ["He", null, "in Busan last year", "."],
        explanation: "<b>last year</b> → 과거시제.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "우리는 다음 주에 그를 방문할 것이다.",
        choices: ["visit", "will visit"],
        correct: 1,
        sentence: ["We", null, "him next week", "."],
        explanation: "<b>next week</b> → 미래시제.",
      },
      {
        id: "e1",
        type: "error",
        ko: "그녀는 매일 영어를 공부한다.",
        tokens: ["She", "study", "English", "every", "day", "."],
        wrongIndex: 1,
        fix: "studies",
        explanation: "3인칭 단수 현재 → <code>studies</code>.",
      },
      {
        id: "e2",
        type: "error",
        ko: "우리는 어제 늦었다.",
        tokens: ["We", "was", "late", "yesterday", "."],
        wrongIndex: 1,
        fix: "were",
        explanation: "복수 주어 <b>We</b>의 과거 → <code>were</code>.",
      },
    ],
  },
];
