// part6Tense2 — 콘텐츠 파일. 형식은 src/content/schema.js 참고.

export const part6Tense2 = [
  {
    id: "tense-prog",
    title: "진행시제 — 진행 중인 동작",
    kind: "basic",
    short: "진행",
    blurb: "be + V-ing — 어떤 시점에 진행 중",
    summary: [
      { t: "h", text: "형태" },
      { t: "p", text: "진행시제 = <b>be동사 + 동사ing</b>. be동사의 시제에 따라 현재/과거/미래로 갈라집니다." },
      {
        t: "table",
        head: ["시제", "형태", "예시"],
        rows: [
          ["현재진행", "am/are/is + V-ing", "I <b>am reading</b> now."],
          ["과거진행", "was/were + V-ing", "He <b>was sleeping</b> then."],
          ["미래진행", "will be + V-ing", "We <b>will be waiting</b>."],
        ],
      },
      { t: "h", text: "의미" },
      { t: "p", text: "\"그 시점에 ~하는 중\"이라는 뜻. 단순현재(<code>I read books</code>: 평소에 읽음)와 다르게 <b>지금/그때 진행 중</b>임을 강조합니다." },
      { t: "h", text: "주의" },
      { t: "p", text: "• 부정: be + <code>not</code> + V-ing<br> • 의문: be를 주어 앞으로 → <code>Is she reading?</code>" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 지금 책을 읽고 있다.",
        prefix: ["I"],
        answer: ["am reading"],
        suffix: ["a", "book", "now", "."],
        distractors: ["is reading", "read", "reading", "was reading"],
        explanation: "주어 I + 현재 → <code>am + V-ing</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 지금 영어를 공부하고 있다.",
        prefix: ["She"],
        answer: ["is studying"],
        suffix: ["English", "now", "."],
        distractors: ["are studying", "study", "studied", "studying"],
        explanation: "3인칭 단수 + 현재 → <code>is + V-ing</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그들은 그때 축구를 하고 있었다.",
        prefix: ["They"],
        answer: ["were", "playing"],
        suffix: ["soccer", "then", "."],
        distractors: ["are playing", "was playing", "play", "played"],
        explanation: "복수 + 과거 → <code>were + V-ing</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "내가 도착했을 때 그는 자고 있었다.",
        prefix: ["He"],
        answer: ["was sleeping"],
        suffix: ["when", "I", "arrived", "."],
        distractors: ["is sleeping", "were sleeping", "slept", "sleeping"],
        explanation: "3인칭 단수 + 과거 → <code>was + V-ing</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "우리는 그때 너를 기다리고 있을 거야.",
        prefix: ["We"],
        answer: ["will", "be", "waiting"],
        suffix: ["for", "you", "then", "."],
        distractors: ["will wait", "are waiting", "be waiting", "will waiting"],
        explanation: "미래진행 → <code>will be + V-ing</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "지금 비가 오고 있니?",
        answer: ["Is"],
        suffix: ["it", "raining", "now", "?"],
        distractors: ["Are", "Does", "Do", "Was"],
        explanation: "현재진행 의문문 — be(it→is)를 주어 앞으로.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그들은 어제 9시에 공부하고 있지 않았다.",
        prefix: ["They"],
        answer: ["were", "not", "studying"],
        suffix: ["at", "9", "yesterday", "."],
        distractors: ["are not studying", "didn't study", "wasn't studying", "don't study"],
        explanation: "복수 + 과거 + 부정 → <code>were not + V-ing</code>.",
      },
    ],
  },

  {
    id: "present-perfect",
    title: "현재완료 — have/has + p.p",
    kind: "basic",
    short: "현재완료",
    blurb: "과거의 일이 현재까지 이어지거나 영향을 미침",
    summary: [
      { t: "h", text: "형태" },
      { t: "p", text: "<b>have/has + 과거분사(p.p)</b>. 주어가 3인칭 단수면 <code>has</code>, 그 외엔 <code>have</code>." },
      { t: "h", text: "의미 (네 가지 용법)" },
      {
        t: "table",
        head: ["용법", "키워드", "예시"],
        rows: [
          ["경험", "ever, never, before", "I <b>have been</b> to Paris."],
          ["완료", "just, already, yet", "She <b>has just arrived</b>."],
          ["계속", "for, since", "We <b>have lived</b> here for 10 years."],
          ["결과", "—", "He <b>has lost</b> his keys. (지금도 없음)"],
        ],
      },
      { t: "h", text: "단순과거와의 차이" },
      { t: "p", text: "단순과거(<code>I went to Paris last year</code>)는 <b>과거의 한 시점에 끝난 일</b>. 현재완료(<code>I have been to Paris</code>)는 <b>지금까지의 경험·상태</b>를 말합니다." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 파리에 가본 적이 있다.",
        prefix: ["I"],
        answer: ["have", "been"],
        suffix: ["to", "Paris", "."],
        distractors: ["have went", "has been", "am been", "have gone"],
        explanation: "경험을 나타내는 현재완료. <code>have been to ~</code>는 \"~에 가본 적 있다\"는 관용 표현.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 막 도착했다.",
        prefix: ["She"],
        answer: ["has", "just", "arrived"],
        suffix: ["."],
        distractors: ["have just arrived", "is just arrived", "just arrived", "did just arrive"],
        explanation: "3인칭 단수 → <code>has</code>. <code>just</code>는 have/has와 p.p 사이.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "우리는 10년 동안 여기 살았다.",
        prefix: ["We"],
        answer: ["have lived"],
        suffix: ["here", "for", "10", "years", "."],
        distractors: ["lived", "have living", "are lived", "had lived"],
        explanation: "계속 용법 — <code>for + 기간</code>과 함께. 과거부터 지금까지.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그는 아직 숙제를 끝내지 못했다.",
        prefix: ["He"],
        answer: ["has", "not", "finished"],
        suffix: ["his", "homework", "yet", "."],
        distractors: ["have not finished", "is not finished", "did not finish", "not has finished"],
        explanation: "완료 부정 — <code>has + not + p.p</code>. <code>yet</code>은 부정문에서 \"아직\".",
      },
      {
        id: "q5",
        type: "blank",
        ko: "너는 그 영화를 본 적 있니?",
        answer: ["Have"],
        suffix: ["you", "seen", "that", "movie", "?"],
        distractors: ["Has", "Did", "Do", "Are"],
        explanation: "현재완료 의문문 — have/has를 주어 앞으로. 주어 you → <code>Have</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그들은 작년부터 한국에서 살고 있다.",
        prefix: ["They"],
        answer: ["have lived"],
        suffix: ["in", "Korea", "since", "last", "year", "."],
        distractors: ["are lived", "lived", "has lived", "have living"],
        explanation: "계속 용법 — <code>since + 시점</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그녀는 그 책을 세 번 읽었다.",
        prefix: ["She"],
        answer: ["has read"],
        suffix: ["the", "book", "three", "times", "."],
        distractors: ["have read", "read", "is reading", "did read"],
        explanation: "경험·횟수를 나타내는 현재완료. <code>read</code>의 p.p는 read(발음만 다름).",
      },
    ],
  },

  {
    id: "past-perfect",
    title: "과거완료 — had + p.p",
    kind: "basic",
    short: "과거완료",
    blurb: "과거의 한 시점보다 더 이전 (대과거)",
    summary: [
      { t: "h", text: "형태" },
      { t: "p", text: "<b>had + 과거분사</b>. 주어와 무관하게 항상 <code>had</code>." },
      { t: "h", text: "의미" },
      { t: "p", text: "과거의 한 시점이 있고, <b>그보다 더 이전</b>에 일어난 일을 말할 때 씁니다." },
      { t: "p", text: "시간선: <code>대과거(had + p.p)</code> → <code>과거(단순과거)</code> → <code>현재</code>" },
      { t: "h", text: "예시" },
      { t: "p", text: "When I <b>arrived</b>, he <b>had already left</b>.<br> (내가 도착했을 때 = 과거 / 그가 떠난 것 = 그 이전 = 대과거)" },
      { t: "h", text: "현재완료와의 차이" },
      { t: "p", text: "• 현재완료(have + p.p): 과거 ~ <b>현재</b>까지<br> • 과거완료(had + p.p): 더 이전 ~ <b>과거 시점</b>까지" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "내가 도착했을 때, 그는 이미 떠난 후였다.",
        prefix: ["When", "I", "arrived", ",", "he"],
        answer: ["had", "already", "left"],
        suffix: ["."],
        distractors: ["has already left", "already left", "was already left", "had already leave"],
        explanation: "도착(과거)보다 더 이전 → 과거완료. <code>already</code>는 had와 p.p 사이.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 그 영화를 본 적이 없다고 말했다.",
        prefix: ["She", "said", "she"],
        answer: ["had", "never", "seen"],
        suffix: ["the", "movie", "."],
        distractors: ["has never seen", "never saw", "didn't see", "had never see"],
        explanation: "말한 것(과거)보다 더 이전의 경험 → 과거완료.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "우리가 도착하기 전에 그들은 이미 식사를 마쳤다.",
        prefix: ["They"],
        answer: ["had", "already", "eaten"],
        suffix: ["before", "we", "arrived", "."],
        distractors: ["have already eaten", "already ate", "were already eating", "had already eat"],
        explanation: "<code>before + 과거</code>가 있으면, 그 이전 일은 과거완료.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "내가 그를 만났을 때, 그는 한국에서 5년을 살았었다.",
        prefix: ["When", "I", "met", "him", ",", "he"],
        answer: ["had lived"],
        suffix: ["in", "Korea", "for", "5", "years", "."],
        distractors: ["has lived", "lived", "was living", "had living"],
        explanation: "만났을 때(과거)까지 이어진 거주 → 과거완료의 계속 용법.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그는 자기가 잃어버린 열쇠를 찾았다.",
        prefix: ["He", "found", "the", "keys", "he"],
        answer: ["had lost"],
        suffix: ["."],
        distractors: ["has lost", "lost", "was lost", "had losing"],
        explanation: "찾은 것(과거)보다 잃어버린 것이 먼저 → 과거완료.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "비가 그쳤을 때 우리는 떠났다.",
        prefix: ["We", "left", "when", "it"],
        answer: ["had stopped"],
        suffix: ["raining", "."],
        distractors: ["has stopped", "stopped", "was stopped", "had stop"],
        explanation: "떠난 시점(과거) 전에 비가 그침 → 과거완료.",
      },
    ],
  },

  {
    id: "future-perfect-progressive",
    title: "미래완료 · 완료진행",
    kind: "basic",
    short: "미래완료",
    blurb: "will have p.p / have been V-ing — 시제의 마지막 조각",
    summary: [
      { t: "h", text: "미래완료 — will have + p.p" },
      { t: "p", text: "미래의 어느 시점까지 <b>완료·경험·계속</b>될 일을 나타냅니다. 기준 시점을 <code>by + 시점</code>으로 명시하는 게 흔합니다." },
      { t: "p", text: "예: <b>By next year</b>, I <b>will have lived</b> here for 10 years. (내년이면 여기 산 지 10년이 된다)" },
      { t: "h", text: "완료진행 — 계속 + 진행의 강조" },
      { t: "p", text: "완료시제는 \"계속\"의 뉘앙스가 있지만, <b>지금까지 (기준 시점까지) 쭉 진행 중이었다</b>는 걸 강조하고 싶을 때 완료진행을 씁니다." },
      {
        t: "table",
        head: ["시제", "형태", "예시"],
        rows: [
          ["현재완료진행", "have/has <b>been + V-ing</b>", "I <b>have been studying</b> for 3 hours."],
          ["과거완료진행", "had <b>been + V-ing</b>", "I <b>had been waiting</b> for an hour when he came."],
          ["미래완료진행", "will have <b>been + V-ing</b>", "By 5, I <b>will have been working</b> for 8 hours."],
        ],
      },
      { t: "h", text: "완료 vs 완료진행 감각 차이" },
      { t: "p", text: "• <code>I have read the book.</code> (완료 — 다 읽었다)<br> • <code>I have been reading the book.</code> (완료진행 — 지금까지 읽고 있다, 계속 중)" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "내년이면 나는 여기서 10년을 산 셈이 될 것이다.",
        prefix: ["By", "next", "year", ",", "I"],
        answer: ["will", "have", "lived"],
        suffix: ["here", "for", "10", "years", "."],
        distractors: ["will live", "have lived", "will living", "will has lived"],
        explanation: "미래의 어느 시점까지의 계속 → <code>will have + p.p</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "나는 3시간 동안 공부하고 있다.",
        prefix: ["I"],
        answer: ["have", "been", "studying"],
        suffix: ["for", "three", "hours", "."],
        distractors: ["have studied", "am studying", "had been studying", "have being studying"],
        explanation: "지금까지 쭉 진행 중 → 현재완료진행 <code>have been + V-ing</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그가 왔을 때 나는 한 시간을 기다리고 있었다.",
        prefix: ["I"],
        answer: ["had", "been", "waiting"],
        suffix: ["for", "an", "hour", "when", "he", "came", "."],
        distractors: ["was waiting", "have been waiting", "had waited", "had waiting"],
        explanation: "과거 시점까지 계속 진행 → 과거완료진행 <code>had been + V-ing</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "8시까지 우리는 그 프로젝트를 끝냈을 것이다.",
        prefix: ["By", "8", ",", "we"],
        answer: ["will", "have", "finished"],
        suffix: ["the", "project", "."],
        distractors: ["will finish", "have finished", "would have finished", "will has finished"],
        explanation: "미래 시점까지의 완료 → <code>will have + p.p</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그녀는 2010년부터 여기서 일해오고 있다.",
        prefix: ["She"],
        answer: ["has", "been", "working"],
        suffix: ["here", "since", "2010", "."],
        distractors: ["has worked", "is working", "had been working", "will have worked"],
        explanation: "since + 과거 시점 + 지금까지 계속 진행 → 현재완료진행.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그가 나에게 전화했을 때 그들은 두 시간 동안 이야기하고 있었다.",
        prefix: ["They"],
        answer: ["had", "been", "talking"],
        suffix: ["for", "two", "hours", "when", "he", "called", "."],
        distractors: ["were talking", "have been talking", "had talked", "would talk"],
        explanation: "과거 특정 시점까지의 진행 계속 → 과거완료진행.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "다음 달까지 나는 여기서 5년째 일하는 셈이 될 것이다.",
        prefix: ["By", "next", "month", ",", "I"],
        answer: ["will", "have", "been", "working"],
        suffix: ["here", "for", "5", "years", "."],
        distractors: ["will work", "have been working", "will have worked", "would have worked"],
        explanation: "미래 시점까지 계속 진행 → 미래완료진행 <code>will have been + V-ing</code>.",
      },
    ],
  },

  {
    id: "tense2-review",
    title: "진행·완료 통합 정리",
    kind: "review",
    short: "통합정리",
    blurb: "진행시제와 완료시제 종합",
    summary: [
      { t: "h", text: "한 화면 정리" },
      {
        t: "table",
        head: ["시제", "형태", "대표 의미"],
        rows: [
          ["현재진행", "am/are/is + V-ing", "지금 ~하는 중"],
          ["과거진행", "was/were + V-ing", "그때 ~하는 중이었다"],
          ["미래진행", "will be + V-ing", "그때 ~하는 중일 것이다"],
          ["현재완료", "have/has + p.p", "과거~현재 경험·완료·계속·결과"],
          ["과거완료", "had + p.p", "과거의 더 이전 (대과거)"],
        ],
      },
      { t: "h", text: "혼동 포인트" },
      { t: "p", text: "• 단순과거 vs 현재완료: 시점 명시(<code>yesterday</code>) → 단순과거 / 시점 없이 경험·계속 → 현재완료<br> • 현재완료 vs 과거완료: 기준이 <b>현재</b>면 have, <b>과거</b>면 had" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그녀는 지금 노래를 부르고 있다.",
        prefix: ["She"],
        answer: ["is", "singing"],
        suffix: ["a", "song", "now", "."],
        distractors: ["sings", "sang", "was singing", "has sung"],
        explanation: "<code>now</code> + 진행 중 → 현재진행.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "나는 너를 두 번 만났다.",
        prefix: ["I"],
        answer: ["have met"],
        suffix: ["you", "twice", "."],
        distractors: ["met", "had met", "am meeting", "have meet"],
        explanation: "횟수 + 경험 → 현재완료.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그가 전화했을 때 나는 자고 있었다.",
        prefix: ["I"],
        answer: ["was", "sleeping"],
        suffix: ["when", "he", "called", "."],
        distractors: ["slept", "have slept", "am sleeping", "had slept"],
        explanation: "과거의 어느 순간 진행 중 → 과거진행.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "내가 도착하기 전에 그는 이미 떠난 후였다.",
        prefix: ["He"],
        answer: ["had", "already", "left"],
        suffix: ["before", "I", "arrived", "."],
        distractors: ["has already left", "left already", "is already left", "was already left"],
        explanation: "도착(과거)보다 이전의 떠남 → 과거완료.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그들은 2020년부터 한국에 살고 있다.",
        prefix: ["They"],
        answer: ["have lived"],
        suffix: ["in", "Korea", "since", "2020", "."],
        distractors: ["lived", "are living", "had lived", "have living"],
        explanation: "<code>since + 시점</code> 과거~현재 계속 → 현재완료.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "내일 이 시간에 우리는 시험을 보고 있을 거다.",
        prefix: ["We"],
        answer: ["will", "be", "taking"],
        suffix: ["the", "test", "this", "time", "tomorrow", "."],
        distractors: ["will take", "are taking", "have taken", "will took"],
        explanation: "미래 어느 순간 진행 → 미래진행.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "너는 그 책을 다 읽었니?",
        answer: ["Have"],
        suffix: ["you", "finished", "the", "book", "?"],
        distractors: ["Did", "Are", "Had", "Do"],
        explanation: "완료 여부를 묻는 현재완료 의문.",
      },
      {
        id: "c1",
        type: "choice",
        ko: "나는 그를 세 번 만났다.",
        choices: ["met", "have met"],
        correct: 1,
        sentence: ["I", null, "him three times", "."],
        explanation: "<b>three times</b>처럼 지금까지의 경험 → 현재완료.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "그녀는 지금 자고 있다.",
        choices: ["is sleeping", "sleeps"],
        correct: 0,
        sentence: ["She", null, "now", "."],
        explanation: "<b>now</b> — 지금 진행 중인 동작 → 현재진행.",
      },
      {
        id: "e1",
        type: "error",
        ko: "우리는 10년 동안 여기 살았다.",
        tokens: ["We", "have", "lived", "here", "since", "10", "years", "."],
        wrongIndex: 4,
        fix: "for",
        explanation: "기간에는 <code>for</code>, 시작 시점에는 <code>since</code>.",
      },
      {
        id: "e2",
        type: "error",
        ko: "그는 파리에 가버렸다.",
        tokens: ["He", "has", "went", "to", "Paris", "."],
        wrongIndex: 2,
        fix: "gone",
        explanation: "현재완료에는 과거분사 <code>gone</code>.",
      },
    ],
  },

  {
    id: "tense-all-mega",
    title: "전체 시제 대왕정리",
    kind: "mega",
    short: "전체 총정리",
    blurb: "단순 · 진행 · 완료 — 모든 시제 종합",
    summary: [
      { t: "h", text: "시제 8가지 한눈에" },
      {
        t: "table",
        head: ["", "단순", "진행", "완료"],
        rows: [
          ["현재", "do / does", "am/are/is V-ing", "have/has p.p"],
          ["과거", "V-ed", "was/were V-ing", "had p.p"],
          ["미래", "will V", "will be V-ing", "—"],
        ],
      },
      { t: "h", text: "선택의 핵심 질문" },
      { t: "p", text: "1) <b>언제</b>의 일인가? → 현재/과거/미래<br> 2) <b>그 시점에 진행 중</b>인가? → 진행시제<br> 3) <b>이전부터 이어진 경험·결과</b>인가? → 완료시제" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그는 매일 아침 운동한다.",
        prefix: ["He"],
        answer: ["exercises"],
        suffix: ["every", "morning", "."],
        distractors: ["exercise", "is exercising", "exercised", "has exercised"],
        explanation: "반복적 습관 → 단순현재. 3인칭 단수 → +s.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "어제 우리는 영화를 봤다.",
        prefix: ["We"],
        answer: ["watched"],
        suffix: ["a", "movie", "yesterday", "."],
        distractors: ["watch", "have watched", "are watching", "had watched"],
        explanation: "<code>yesterday</code> 명시 → 단순과거.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "나는 지금 점심을 먹고 있다.",
        prefix: ["I"],
        answer: ["am", "eating"],
        suffix: ["lunch", "now", "."],
        distractors: ["eat", "have eaten", "ate", "was eating"],
        explanation: "지금 진행 중 → 현재진행.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그녀는 결혼한 적이 없다.",
        prefix: ["She"],
        answer: ["has", "never", "married"],
        suffix: ["."],
        distractors: ["never married", "have never married", "is never married", "had never married"],
        explanation: "경험 부정 → 현재완료 + <code>never</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "내가 그를 봤을 때 그는 울고 있었다.",
        prefix: ["He"],
        answer: ["was", "crying"],
        suffix: ["when", "I", "saw", "him", "."],
        distractors: ["cried", "has cried", "is crying", "had cried"],
        explanation: "과거의 한 순간 진행 중 → 과거진행.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "버스가 도착했을 때 우리는 이미 30분을 기다린 상태였다.",
        prefix: ["We"],
        answer: ["had", "already", "waited"],
        suffix: ["for", "30", "minutes", "when", "the", "bus", "came", "."],
        distractors: ["have already waited", "already waited", "were already waiting", "had already wait"],
        explanation: "과거(버스 도착)보다 더 이전부터의 일 → 과거완료.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그들은 내일 너를 방문할 것이다.",
        prefix: ["They"],
        answer: ["will visit"],
        suffix: ["you", "tomorrow", "."],
        distractors: ["visit", "are visiting", "have visited", "will visiting"],
        explanation: "미래 → <code>will + 원형</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "그녀는 이미 그 책을 세 번 읽었다.",
        prefix: ["She"],
        answer: ["has read"],
        suffix: ["the", "book", "three", "times", "."],
        distractors: ["read", "is reading", "had read", "have read"],
        explanation: "경험·횟수 (지금까지) → 현재완료. 3인칭 단수 → has.",
      },
      {
        id: "c1",
        type: "choice",
        ko: "내가 도착했을 때 그는 이미 떠났었다.",
        choices: ["left", "leave"],
        correct: 0,
        sentence: ["When I arrived, he had already", null, "."],
        explanation: "과거완료 <code>had + p.p</code>.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "그들은 내일 이 시간에 공부하고 있을 것이다.",
        choices: ["will be studying", "will studying"],
        correct: 0,
        sentence: ["They", null, "at this time tomorrow", "."],
        explanation: "미래진행 <code>will be + V-ing</code>.",
      },
      {
        id: "e1",
        type: "error",
        ko: "그녀는 3년 동안 영어를 공부했다.",
        tokens: ["She", "has", "study", "English", "for", "3", "years", "."],
        wrongIndex: 2,
        fix: "studied",
        explanation: "현재완료에는 과거분사 <code>studied</code>.",
      },
      {
        id: "e2",
        type: "error",
        ko: "내가 왔을 때 그는 이미 가버렸었다.",
        tokens: ["When", "I", "came", ",", "he", "has", "already", "gone", "."],
        wrongIndex: 5,
        fix: "had",
        explanation: "과거보다 더 앞선 일 → 과거완료 <code>had</code>.",
      },
    ],
  },
];
