// part2Passive — 콘텐츠 파일. 형식은 src/content/schema.js 참고.

export const part2Passive = [
  {
    id: "passive-basic",
    title: "수동태 기본",
    kind: "basic",
    short: "기본",
    blurb: "be + 과거분사 (p.p)",
    summary: [
      { t: "h", text: "수동태란?" },
      { t: "p", text: "주어가 <b>~을 한다</b>(능동) 가 아닌, <b>~당하다 / ~되다</b>로 바뀌는 형태입니다." },
      { t: "p", text: "공식: <b>주어 + be동사 + 과거분사(p.p)</b> + (by 행위자)" },
      {
        t: "table",
        head: ["능동태", "수동태"],
        rows: [
          ["Tom <b>writes</b> a letter.", "A letter <b>is written</b> by Tom."],
          ["She <b>cleans</b> the room.", "The room <b>is cleaned</b>."],
        ],
      },
      { t: "h", text: "핵심 포인트" },
      { t: "p", text: "• be동사는 <b>주어에 맞춰</b> 변합니다 (is / are / was / were)<br> • 동사는 <b>과거분사형(p.p)</b>으로 — write→<code>written</code>, eat→<code>eaten</code><br> • 행위자는 <b>by + 대상</b>, 중요하지 않으면 <b>생략</b>" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "이 책은 많은 사람들에게 읽힌다.",
        prefix: ["This", "book"],
        answer: ["is", "read"],
        suffix: ["by", "many", "people", "."],
        distractors: ["reads", "is reading", "was read", "are read"],
        explanation: "현재 수동 + 단수 → <code>is + p.p (read)</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그 창문은 톰에 의해 깨졌다.",
        prefix: ["The", "window"],
        answer: ["was broken"],
        suffix: ["by", "Tom", "."],
        distractors: ["broke", "is broken", "were broken", "broken"],
        explanation: "과거 수동 + 단수 → <code>was + p.p (broken)</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그 노래들은 학생들에 의해 불려진다.",
        prefix: ["The", "songs"],
        answer: ["are", "sung"],
        suffix: ["by", "students", "."],
        distractors: ["sing", "is sung", "were sung", "sang"],
        explanation: "현재 수동 + 복수 → <code>are + p.p (sung)</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "이 차는 한국에서 만들어졌다.",
        prefix: ["This", "car"],
        answer: ["was made"],
        suffix: ["in", "Korea", "."],
        distractors: ["made", "is made", "were made", "makes"],
        explanation: "과거 수동 + 단수 → <code>was + p.p (made)</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그 편지들은 어제 보내졌다.",
        prefix: ["The", "letters"],
        answer: ["were sent"],
        suffix: ["yesterday", "."],
        distractors: ["sent", "was sent", "are sent", "send"],
        explanation: "과거 수동 + 복수 → <code>were + p.p (sent)</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그 방은 매일 청소된다.",
        prefix: ["The", "room"],
        answer: ["is cleaned"],
        suffix: ["every", "day", "."],
        distractors: ["cleans", "cleaned", "was cleaned", "are cleaned"],
        explanation: "현재 수동 + 단수 → <code>is + p.p (cleaned)</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그 그림은 피카소에 의해 그려졌다.",
        prefix: ["The", "painting"],
        answer: ["was painted"],
        suffix: ["by", "Picasso", "."],
        distractors: ["painted", "is painted", "were painted", "paints"],
        explanation: "과거 수동 + 단수 → <code>was + p.p (painted)</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "영어는 전 세계에서 쓰인다.",
        prefix: ["English"],
        answer: ["is", "spoken"],
        suffix: ["all", "over", "the", "world", "."],
        distractors: ["speaks", "speak", "was spoken", "spoke"],
        explanation: "현재 수동 + 단수 → <code>is + p.p (spoken)</code>.",
      },
    ],
  },

  {
    id: "passive-negq",
    title: "수동태 부정·의문",
    kind: "basic",
    short: "부정·의문",
    blurb: "be동사처럼 다룬다",
    summary: [
      { t: "h", text: "수동태 부정과 의문" },
      { t: "p", text: "수동태의 핵심은 <b>be동사</b>입니다. 부정·의문도 그 be동사를 그대로 활용해요." },
      {
        t: "table",
        head: ["형태", "예시"],
        rows: [
          ["긍정", "The cake <b>is made</b> here."],
          ["부정", "The cake <b>is not made</b> here."],
          ["의문", "<b>Is</b> the cake <b>made</b> here?"],
          ["부정의문", "<b>Isn't</b> the cake <b>made</b> here?"],
        ],
      },
      { t: "p", text: "⚠️ <b>p.p는 그대로 두고</b>, be동사만 변형/이동시킵니다." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "이 책은 학생들에게 읽히지 않는다.",
        prefix: ["This", "book"],
        answer: ["is", "not", "read"],
        suffix: ["by", "students", "."],
        distractors: ["doesn't read", "reads not", "isn't reading", "wasn't"],
        explanation: "현재 수동 부정 → <code>is + not + p.p</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그 문은 닫혀 있었나요?",
        answer: ["Was"],
        suffix: ["the", "door", "closed", "?"],
        distractors: ["Did", "Were", "Is", "Does"],
        explanation: "과거 수동 의문 + 단수 → <code>Was + 주어 + p.p ?</code>",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그 차는 한국에서 만들어지지 않았다.",
        prefix: ["The", "car"],
        answer: ["was", "not", "made"],
        suffix: ["in", "Korea", "."],
        distractors: ["didn't make", "not was made", "wasn't making", "isn't made"],
        explanation: "과거 수동 부정 → <code>was + not + p.p</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그 편지들은 어제 보내졌나요?",
        answer: ["Were"],
        suffix: ["the", "letters", "sent", "yesterday", "?"],
        distractors: ["Was", "Did", "Are", "Do"],
        explanation: "과거 수동 의문 + 복수 → <code>Were + 주어 + p.p ?</code>",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그 노래는 그녀에 의해 불리지 않니?",
        answer: ["Isn't"],
        suffix: ["the", "song", "sung", "by", "her", "?"],
        distractors: ["Doesn't", "Wasn't", "Don't", "Aren't"],
        explanation: "현재 수동 부정의문 + 단수 → <code>Isn't + 주어 + p.p ?</code>",
      },
      {
        id: "q6",
        type: "blank",
        ko: "이 집은 1990년에 지어졌다.",
        prefix: ["This", "house"],
        answer: ["was built"],
        suffix: ["in", "1990", "."],
        distractors: ["built", "is built", "were built", "builds"],
        explanation: "과거 수동 + 단수 → <code>was + p.p (built)</code>.",
      },
    ],
  },

  {
    id: "passive-45",
    title: "4·5형식 수동태",
    kind: "basic",
    short: "4·5형식",
    blurb: "두 개의 목적어·목적격보어가 있는 문장의 수동 전환",
    summary: [
      { t: "h", text: "4형식의 수동태 — 두 가지 방식" },
      { t: "p", text: "4형식(<code>S + V + IO + DO</code>)은 목적어가 두 개라 <b>두 가지 수동태</b>가 가능합니다." },
      {
        t: "table",
        head: ["능동", { text: "He <b>gave me a book</b>.", span: 2 }],
        rows: [
          ["IO를 주어로", "I <b>was given</b> a book (by him).", "~가 ~을 받았다"],
          ["DO를 주어로", "A book <b>was given to me</b> (by him).", "~이 ~에게 주어졌다 (전치사 필요)"],
        ],
      },
      { t: "p", text: "주의: <code>buy, make, cook, get, find</code> 등은 <b>IO 수동태 어색</b> — DO 수동태만 자연스러움." },
      { t: "p", text: "전치사 선택: give·send·show·tell·teach·write는 <b>to</b> / buy·make·get은 <b>for</b>." },
      { t: "h", text: "5형식의 수동태" },
      { t: "p", text: "목적어(O)를 주어로, 목적격보어(OC)는 그대로 두 번째 자리에 남습니다." },
      { t: "p", text: "They elected <b>him</b> <b>president</b>. → <b>He was elected president</b>." },
      { t: "h", text: "지각·사역동사의 함정" },
      { t: "p", text: "능동에서 <b>원형부정사</b>를 쓰던 지각·사역동사(see, hear, watch, make, help)가 수동태로 바뀔 때는 <b>to부정사</b>로 변합니다." },
      { t: "p", text: "They <b>made him work</b>. → He <b>was made to work</b>.<br> I <b>saw him enter</b>. → He <b>was seen to enter</b>." },
      { t: "p", text: "단, <code>let</code>은 수동태로 잘 쓰지 않고 <code>be allowed to</code>로 대체합니다." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 그로부터 책을 받았다.",
        prefix: ["I"],
        answer: ["was", "given"],
        suffix: ["a", "book", "by", "him", "."],
        distractors: ["was gave", "gave", "am given", "was giving"],
        explanation: "4형식 수동태 — IO(me)가 주어. <code>be + p.p</code>. give의 p.p는 <code>given</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그 책은 그에 의해 나에게 주어졌다.",
        prefix: ["The", "book"],
        answer: ["was", "given", "to"],
        suffix: ["me", "by", "him", "."],
        distractors: ["was given for", "gave to", "was given", "gives to"],
        explanation: "4형식 수동태 — DO(a book)를 주어로. give는 <b>to</b>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그는 회장으로 뽑혔다.",
        prefix: ["He"],
        answer: ["was elected"],
        suffix: ["president", "."],
        distractors: ["was elected as", "elected", "was electing", "has elected"],
        explanation: "5형식 수동태 — 목적격보어(president)는 그대로 뒤에 남음. as를 넣지 않는 게 정석.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "나는 그녀에 의해 행복해졌다.",
        prefix: ["I"],
        answer: ["was made"],
        suffix: ["happy", "by", "her", "."],
        distractors: ["was made to", "made", "was making", "have made"],
        explanation: "5형식(She made me happy) 수동태. 형용사 보어 <code>happy</code>는 그대로.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그는 (누군가에 의해) 일하도록 시켜졌다.",
        prefix: ["He"],
        answer: ["was", "made", "to"],
        suffix: ["work", "."],
        distractors: ["was made", "made to", "was making", "had to made"],
        explanation: "사역동사 make의 수동태 — 능동의 원형(work)이 <b>to work</b>로 변함.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그가 방에 들어가는 것이 목격되었다.",
        prefix: ["He"],
        answer: ["was", "seen", "to"],
        suffix: ["enter", "the", "room", "."],
        distractors: ["was seen", "saw to", "was seeing", "has seen"],
        explanation: "지각동사 see의 수동태 — 원형 <code>enter</code>가 <b>to enter</b>로.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그 이야기가 나에게 말해졌다.",
        prefix: ["The", "story"],
        answer: ["was", "told", "to"],
        suffix: ["me", "."],
        distractors: ["was told for", "told me", "was tell", "told to"],
        explanation: "4형식(tell) 수동태 — DO(the story)를 주어로. tell 계열은 <b>to</b>.",
      },
    ],
  },

  {
    id: "passive-advanced",
    title: "심화 수동태 — 시제·조동사·동사구·by 이외 전치사",
    kind: "basic",
    short: "심화",
    blurb: "진행형·완료형 수동태, 관용 전치사(be interested in 등)",
    summary: [
      { t: "h", text: "시제·형태별 수동태" },
      {
        t: "table",
        head: ["형태", "공식", "예시"],
        rows: [
          ["진행형 수동", "be + <b>being</b> + p.p", "The house <b>is being built</b>."],
          ["완료형 수동", "have/has/had + <b>been</b> + p.p", "The car <b>has been repaired</b>."],
          ["조동사 수동", "조동사 + <b>be</b> + p.p", "It <b>must be done</b>."],
          ["미래 수동", "will + <b>be</b> + p.p", "The letter <b>will be sent</b>."],
        ],
      },
      { t: "h", text: "동사구의 수동태 — 통째로 이동" },
      { t: "p", text: "동사 + 전치사·부사가 하나의 동사처럼 쓰이는 경우, <b>전치사·부사까지 함께</b> 옮깁니다." },
      {
        t: "ul",
        items: [
          "People <b>laughed at</b> him. → He <b>was laughed at</b> by people.",
          "She <b>took care of</b> him. → He <b>was taken care of</b>.",
        ],
      },
      { t: "h", text: "by 이외의 전치사 — 관용 표현" },
      {
        t: "table",
        head: ["전치사", "표현"],
        rows: [
          ["<b>in</b>", "be interested <b>in</b> (관심 있다) / be engaged <b>in</b>"],
          ["<b>at</b>", "be surprised <b>at</b> / be shocked <b>at</b> / be amazed <b>at</b>"],
          ["<b>with</b>", "be pleased <b>with</b> / be satisfied <b>with</b> / be covered <b>with</b> / be filled <b>with</b>"],
          ["<b>to</b>", "be known <b>to</b> (~에게 알려진) / be married <b>to</b> / be exposed <b>to</b>"],
          ["<b>about</b>", "be worried <b>about</b> / be concerned <b>about</b>"],
          ["<b>of</b>", "be made <b>of</b> (재료 - 물리 변화 X) / be tired <b>of</b> / be afraid <b>of</b>"],
          ["<b>from</b>", "be made <b>from</b> (재료 - 화학 변화 O)"],
        ],
      },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그 집은 지금 지어지고 있다.",
        prefix: ["The", "house"],
        answer: ["is", "being", "built"],
        suffix: ["now", "."],
        distractors: ["is built", "is building", "has been built", "was being built"],
        explanation: "진행형 수동태 — <code>be + being + p.p</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그 차는 이미 고쳐졌다.",
        prefix: ["The", "car"],
        answer: ["has", "been", "repaired"],
        suffix: ["already", "."],
        distractors: ["has repaired", "was repaired", "is repaired", "had repaired"],
        explanation: "현재완료 수동태 — <code>have/has + been + p.p</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그것은 오늘 끝내져야 한다.",
        prefix: ["It"],
        answer: ["must", "be", "finished"],
        suffix: ["today", "."],
        distractors: ["must finish", "must have finished", "must being finished", "should finished"],
        explanation: "조동사 수동태 — <code>조동사 + be + p.p</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그는 사람들에게 비웃음을 당했다.",
        prefix: ["He"],
        answer: ["was", "laughed", "at"],
        suffix: ["by", "people", "."],
        distractors: ["was laughed", "laughed at", "was laughing at", "has laughed at"],
        explanation: "동사구 <code>laugh at</code>은 통째로 옮김 — <code>be laughed at</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "나는 영어에 관심이 있다.",
        prefix: ["I"],
        answer: ["am", "interested", "in"],
        suffix: ["English", "."],
        distractors: ["am interested by", "interest in", "interested in", "am interesting in"],
        explanation: "관심 → <code>be interested in</code>. by가 아닌 <b>in</b>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그 산은 눈으로 덮여있다.",
        prefix: ["The", "mountain"],
        answer: ["is", "covered", "with"],
        suffix: ["snow", "."],
        distractors: ["is covered by", "covered with", "is covering with", "is covered in"],
        explanation: "덮여있다 → <code>be covered with</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그는 그 사고에 놀랐다.",
        prefix: ["He"],
        answer: ["was", "surprised", "at"],
        suffix: ["the", "accident", "."],
        distractors: ["was surprised by", "surprised at", "was surprising at", "surprises at"],
        explanation: "감정의 원인 → <code>be surprised at/by</code>. 시험에선 <b>at</b>이 정석.",
      },
    ],
  },

  {
    id: "passive-review",
    title: "수동태 통합 정리",
    kind: "review",
    short: "통합정리",
    blurb: "능동 ↔ 수동, 시제별 한꺼번에",
    summary: [
      { t: "h", text: "능동 ↔ 수동 변환 3단계" },
      { t: "p", text: "1) 목적어를 <b>주어</b>로 옮긴다<br> 2) 동사를 <b>be + p.p</b>로 바꾼다 (be동사 시제는 원래 시제에 맞춰)<br> 3) 원래 주어는 <b>by + ...</b>로 (생략 가능)" },
      { t: "h", text: "시제별 수동태" },
      {
        t: "table",
        head: ["시제", "능동", "수동"],
        rows: [
          ["현재", "makes", "<b>is/are made</b>"],
          ["과거", "made", "<b>was/were made</b>"],
          ["미래", "will make", "<b>will be made</b>"],
        ],
      },
      { t: "p", text: "💡 <b>be동사를 시제·수에 맞춰 바꾸는 것</b>이 핵심이에요. p.p는 변하지 않아요." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "이 영화는 많은 사람들에게 사랑받는다.",
        prefix: ["This", "movie"],
        answer: ["is loved"],
        suffix: ["by", "many", "people", "."],
        distractors: ["loves", "loved", "was loved", "are loved"],
        explanation: "현재 수동 + 단수 → <code>is + p.p (loved)</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그 컵들은 어제 깨졌다.",
        prefix: ["The", "cups"],
        answer: ["were", "broken"],
        suffix: ["yesterday", "."],
        distractors: ["broke", "was broken", "are broken", "break"],
        explanation: "과거 수동 + 복수 → <code>were + p.p (broken)</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그 문제는 곧 해결될 것이다.",
        prefix: ["The", "problem"],
        answer: ["will", "be", "solved"],
        suffix: ["soon", "."],
        distractors: ["will solve", "solves", "is solved", "was solved"],
        explanation: "미래 수동 → <code>will + be + p.p (solved)</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "이 펜은 사용되지 않는다.",
        prefix: ["This", "pen"],
        answer: ["is", "not", "used"],
        suffix: ["."],
        distractors: ["doesn't use", "isn't using", "wasn't", "not is"],
        explanation: "현재 수동 부정 + 단수 → <code>is + not + p.p</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그 책은 학생들에 의해 쓰여졌니?",
        answer: ["Was"],
        suffix: ["the", "book", "written", "by", "students", "?"],
        distractors: ["Did", "Were", "Is", "Does"],
        explanation: "과거 수동 의문 + 단수 → <code>Was + 주어 + p.p ?</code>",
      },
      {
        id: "q6",
        type: "blank",
        ko: "이 차들은 독일에서 만들어진다.",
        prefix: ["These", "cars"],
        answer: ["are made"],
        suffix: ["in", "Germany", "."],
        distractors: ["make", "is made", "were made", "made"],
        explanation: "현재 수동 + 복수 → <code>are + p.p (made)</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그 방은 매일 청소되지 않니?",
        answer: ["Isn't"],
        suffix: ["the", "room", "cleaned", "every", "day", "?"],
        distractors: ["Doesn't", "Wasn't", "Aren't", "Don't"],
        explanation: "현재 수동 부정의문 + 단수 → <code>Isn't + 주어 + p.p ?</code>",
      },
      {
        id: "c1",
        type: "choice",
        ko: "이 편지는 어제 쓰여졌다.",
        choices: ["was written", "was wrote"],
        correct: 0,
        sentence: ["This letter", null, "yesterday", "."],
        explanation: "수동태는 <code>be + 과거분사</code> — write의 p.p 는 <code>written</code>.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "그 방은 매일 청소된다.",
        choices: ["is cleaned", "is cleaning"],
        correct: 0,
        sentence: ["The room", null, "every day", "."],
        explanation: "방이 청소를 '당하는' 쪽이므로 수동태.",
      },
      {
        id: "e1",
        type: "error",
        ko: "그 창문은 톰에 의해 깨졌다.",
        tokens: ["The", "window", "was", "broke", "by", "Tom", "."],
        wrongIndex: 3,
        fix: "broken",
        explanation: "<b>broke</b>는 과거형이고, 수동태에는 과거분사 <code>broken</code>이 필요하다.",
      },
      {
        id: "e2",
        type: "error",
        ko: "이 차들은 독일에서 만들어진다.",
        tokens: ["These", "cars", "is", "made", "in", "Germany", "."],
        wrongIndex: 2,
        fix: "are",
        explanation: "주어가 복수 <b>These cars</b> → <code>are</code>.",
      },
    ],
  },
];
