// part4Connect — 콘텐츠 파일. 형식은 src/content/schema.js 참고.

export const part4Connect = [
  {
    id: "conjunction",
    title: "접속사 — 단어·문장을 잇다",
    kind: "basic",
    short: "접속사",
    blurb: "and / but / or / because / when / if",
    summary: [
      { t: "h", text: "등위접속사 — 같은 무게의 것을 잇는다" },
      {
        t: "table",
        head: ["접속사", "의미", "예시"],
        rows: [
          ["<b>and</b>", "그리고", "I like tea <b>and</b> coffee."],
          ["<b>but</b>", "그러나", "It's cheap, <b>but</b> good."],
          ["<b>or</b>", "또는", "Tea <b>or</b> coffee?"],
          ["<b>so</b>", "그래서", "I was tired, <b>so</b> I slept."],
        ],
      },
      { t: "h", text: "종속접속사 — 한쪽이 다른 쪽에 붙는다" },
      {
        t: "table",
        head: ["접속사", "의미"],
        rows: [
          ["<b>because</b>", "~때문에 (이유)"],
          ["<b>when</b>", "~할 때 (시간)"],
          ["<b>if</b>", "~한다면 (조건)"],
          ["<b>although / though</b>", "비록 ~지만"],
        ],
      },
      { t: "p", text: "⚠️ <b>because of</b>(전치사구) 뒤에는 <b>명사</b>, <b>because</b>(접속사) 뒤에는 <b>주어+동사</b>." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 차와 커피를 좋아한다.",
        prefix: ["I", "like", "tea"],
        answer: ["and"],
        suffix: ["coffee", "."],
        distractors: ["but", "or", "so", "because"],
        explanation: "둘을 함께 → <code>and</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그것은 싸지만 좋다.",
        prefix: ["It", "is", "cheap", ","],
        answer: ["but"],
        suffix: ["good", "."],
        distractors: ["and", "or", "so", "because"],
        explanation: "역접(반대 의미) → <code>but</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "차 또는 커피?",
        prefix: ["Tea"],
        answer: ["or"],
        suffix: ["coffee", "?"],
        distractors: ["and", "but", "so", "because"],
        explanation: "선택 → <code>or</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "나는 피곤해서 잤다.",
        prefix: ["I", "was", "tired", ","],
        answer: ["so"],
        suffix: ["I", "slept", "."],
        distractors: ["because", "and", "but", "if"],
        explanation: "원인 → 결과 → <code>so</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "비가 와서 우산을 가지고 갔다.",
        prefix: ["I", "took", "an", "umbrella"],
        answer: ["because"],
        suffix: ["it", "rained", "."],
        distractors: ["so", "but", "and", "or"],
        explanation: "이유를 뒤에 붙임 → <code>because + 주어 + 동사</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "내가 어렸을 때 시골에 살았다.",
        answer: ["When"],
        suffix: ["I", "was", "young", ",", "I", "lived", "in", "the", "country", "."],
        distractors: ["If", "Because", "So", "But"],
        explanation: "시간 (~할 때) → <code>When</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "내일 비가 오면 집에 있을게.",
        answer: ["If"],
        suffix: ["it", "rains", "tomorrow", ",", "I", "will", "stay", "home", "."],
        distractors: ["When", "Because", "So", "But"],
        explanation: "조건 (~한다면) → <code>If</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "비록 피곤했지만, 그는 공부했다.",
        answer: ["Although"],
        suffix: ["he", "was", "tired", ",", "he", "studied", "."],
        distractors: ["Because", "If", "So", "When"],
        explanation: "양보 (비록 ~지만) → <code>Although</code>.",
      },
    ],
  },

  {
    id: "preposition",
    title: "전치사 — 시간·장소를 표시",
    kind: "basic",
    short: "전치사",
    blurb: "in / on / at / to / from",
    summary: [
      { t: "h", text: "시간 전치사 — <b>큰 → 작은</b> 순으로 좁힌다" },
      {
        t: "table",
        head: ["크기", "전치사", "예시"],
        rows: [
          ["큼 (월/연도/계절)", "<b>in</b>", "in May, in 2025, in winter"],
          ["중간 (요일/날짜)", "<b>on</b>", "on Monday, on July 4th"],
          ["작음 (시각)", "<b>at</b>", "at 7 o'clock, at noon"],
        ],
      },
      { t: "h", text: "장소 전치사 — 같은 in/on/at, 다른 감각" },
      {
        t: "table",
        head: ["전치사", "이미지", "예시"],
        rows: [
          ["<b>in</b>", "안쪽 (3차원 공간)", "in Seoul, in the box"],
          ["<b>on</b>", "붙어 있음 (면)", "on the table, on the wall"],
          ["<b>at</b>", "한 점/지점", "at the door, at school"],
        ],
      },
      { t: "h", text: "방향·기타" },
      { t: "p", text: "<b>to</b> ~로 (방향), <b>from</b> ~로부터, <b>for</b> ~동안/위해, <b>with</b> ~와 함께, <b>by</b> ~에 의해/옆에" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 7시에 일어난다.",
        prefix: ["I", "get", "up"],
        answer: ["at"],
        suffix: ["7", "o'clock", "."],
        distractors: ["in", "on", "to", "by"],
        explanation: "시각(작은 시간) → <code>at</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "우리는 월요일에 만난다.",
        prefix: ["We", "meet"],
        answer: ["on"],
        suffix: ["Monday", "."],
        distractors: ["in", "at", "to", "by"],
        explanation: "요일·날짜 → <code>on</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그는 2025년에 졸업했다.",
        prefix: ["He", "graduated"],
        answer: ["in"],
        suffix: ["2025", "."],
        distractors: ["on", "at", "to", "by"],
        explanation: "연도(큰 시간) → <code>in</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "책이 책상 위에 있다.",
        prefix: ["The", "book", "is"],
        answer: ["on"],
        suffix: ["the", "desk", "."],
        distractors: ["in", "at", "to", "by"],
        explanation: "면에 붙어 있음 → <code>on</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그는 서울에 산다.",
        prefix: ["He", "lives"],
        answer: ["in"],
        suffix: ["Seoul", "."],
        distractors: ["on", "at", "to", "by"],
        explanation: "도시·국가는 공간 안 → <code>in</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그녀는 학교에 있다.",
        prefix: ["She", "is"],
        answer: ["at"],
        suffix: ["school", "."],
        distractors: ["in", "on", "to", "by"],
        explanation: "위치를 한 점으로 → <code>at school</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "나는 부산으로 갔다.",
        prefix: ["I", "went"],
        answer: ["to"],
        suffix: ["Busan", "."],
        distractors: ["in", "on", "at", "for"],
        explanation: "방향(~로) → <code>to</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "그는 친구와 함께 공부한다.",
        prefix: ["He", "studies"],
        answer: ["with"],
        suffix: ["his", "friend", "."],
        distractors: ["by", "to", "for", "from"],
        explanation: "동반(~와 함께) → <code>with</code>.",
      },
      {
        id: "q9",
        type: "blank",
        ko: "그 편지는 톰에 의해 쓰여졌다.",
        prefix: ["The", "letter", "was", "written"],
        answer: ["by"],
        suffix: ["Tom", "."],
        distractors: ["with", "to", "from", "for"],
        explanation: "수동태의 행위자 → <code>by</code>.",
      },
    ],
  },

  {
    id: "modal",
    title: "조동사 — 동사에 의미를 더한다",
    kind: "basic",
    short: "기본",
    group: "조동사",
    blurb: "can / will / must / should / may",
    summary: [
      { t: "h", text: "조동사 = 동사를 돕는 동사" },
      { t: "p", text: "공식: <b>조동사 + 동사원형</b>. 주어가 he/she여도 <b>-s 안 붙임</b>!" },
      {
        t: "table",
        head: ["조동사", "의미", "예시"],
        rows: [
          ["<b>can</b>", "~할 수 있다 (능력)", "I <b>can</b> swim."],
          ["<b>will</b>", "~할 것이다 (미래)", "I <b>will</b> go."],
          ["<b>must</b>", "~해야 한다 (의무)", "You <b>must</b> stop."],
          ["<b>should</b>", "~하는 게 좋다 (충고)", "You <b>should</b> rest."],
          ["<b>may</b>", "~일지도 모른다 / 해도 된다", "It <b>may</b> rain."],
          ["<b>have to</b>", "~해야 한다 (의무)", "I <b>have to</b> go."],
        ],
      },
      { t: "h", text: "부정·의문" },
      { t: "p", text: "부정: <code>조동사 + not + 원형</code> — can't, won't, mustn't, shouldn't<br> 의문: <code>조동사 + 주어 + 원형 ?</code>" },
      { t: "p", text: "⚠️ <b>must</b> vs <b>have to</b>: 의미는 비슷하지만 — must의 부정 <b>mustn't</b>는 \"절대 ~하지 마라\"(금지),<br> have to의 부정 <b>don't have to</b>는 \"~할 필요 없다\"(불필요)." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 수영할 수 있다.",
        prefix: ["I"],
        answer: ["can", "swim"],
        suffix: ["."],
        distractors: ["can swims", "swim can", "am swim", "could swim"],
        explanation: "<code>조동사 + 동사원형</code> → <code>can + swim</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀는 한국어를 할 수 있다.",
        prefix: ["She"],
        answer: ["can", "speak"],
        suffix: ["Korean", "."],
        distractors: ["can speaks", "cans speak", "is speak", "speaks can"],
        explanation: "주어가 she여도 <b>cans</b>·<b>can speaks</b>는 ✗ — 그냥 <code>can speak</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "너는 멈춰야 한다.",
        prefix: ["You"],
        answer: ["must", "stop"],
        suffix: ["."],
        distractors: ["must stops", "must stopped", "musts stop", "should stops"],
        explanation: "<code>must + 원형</code> → <code>must stop</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "너는 좀 쉬는 게 좋겠다.",
        prefix: ["You"],
        answer: ["should", "rest"],
        suffix: ["."],
        distractors: ["should rests", "shoulds rest", "should resting", "rest should"],
        explanation: "충고 → <code>should + 원형</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "내일 비가 올지도 모른다.",
        prefix: ["It"],
        answer: ["may", "rain"],
        suffix: ["tomorrow", "."],
        distractors: ["may rains", "mays rain", "is may rain", "rains may"],
        explanation: "추측 → <code>may + 원형</code>. 주어가 it이어도 rains 아님!",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그는 수영을 할 수 없다.",
        prefix: ["He"],
        answer: ["can't", "swim"],
        suffix: ["."],
        distractors: ["cans't swim", "don't can swim", "isn't swim", "can swims not"],
        explanation: "조동사 부정 → <code>can + not = can't</code> + 원형.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "너는 한국어 할 수 있니?",
        answer: ["Can"],
        suffix: ["you", "speak", "Korean", "?"],
        distractors: ["Do", "Are", "Will", "Should"],
        explanation: "조동사 의문 → <code>조동사 + 주어 + 원형 ?</code>",
      },
      {
        id: "q8",
        type: "blank",
        ko: "나는 지금 가야 한다.",
        prefix: ["I"],
        answer: ["have", "to", "go"],
        suffix: ["now", "."],
        distractors: ["have go", "must to go", "should to go", "has to go"],
        explanation: "<code>have to + 원형</code>. (주어 I → have, he/she → has to)",
      },
    ],
  },

  {
    id: "modal-have-pp",
    title: "조동사 + have + p.p — 과거에 대한 추측·후회",
    kind: "basic",
    short: "have+p.p",
    group: "조동사",
    blurb: "should have / must have / could have — 지나간 일에 대한 판단",
    summary: [
      { t: "h", text: "조동사 + have + p.p 란?" },
      { t: "p", text: "<b>조동사 + have + 과거분사</b> 형태로, 과거 일에 대한 <b>지금의 판단·후회·추측</b>을 나타냅니다." },
      {
        t: "table",
        head: ["패턴", "의미", "예시"],
        rows: [
          ["<code>must have p.p</code>", "~했음이 틀림없다 (강한 확신)", "He <b>must have been</b> sick."],
          ["<code>cannot have p.p</code>", "~했을 리 없다", "She <b>cannot have said</b> that."],
          ["<code>may/might have p.p</code>", "~했을지도 모른다 (약한 추측)", "You <b>may have missed</b> the bus."],
          ["<code>should have p.p</code>", "~했어야 했다 (후회·아쉬움)", "I <b>should have studied</b> harder."],
          ["<code>shouldn't have p.p</code>", "~하지 말았어야 했다", "I <b>shouldn't have sent</b> that letter."],
          ["<code>could have p.p</code>", "~할 수도 있었다 (안 했음)", "He <b>could have helped</b> us."],
          ["<code>would have p.p</code>", "(가정) ~했을 것이다", "I <b>would have gone</b>, but I was busy."],
        ],
      },
      { t: "h", text: "핵심 감각" },
      { t: "p", text: "모두 <b>이미 지나간 일</b>에 대해 지금 말하는 것. 실제 그 일이 일어났는지 여부는 조동사에 따라 달라집니다." },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "그는 아팠음이 틀림없다.",
        prefix: ["He"],
        answer: ["must", "have", "been"],
        suffix: ["sick", "."],
        distractors: ["must be", "must have being", "had to be", "must been"],
        explanation: "과거의 강한 확신 → <code>must have + p.p</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "나는 더 공부했어야 했다.",
        prefix: ["I"],
        answer: ["should", "have", "studied"],
        suffix: ["harder", "."],
        distractors: ["should study", "must have studied", "had studied", "should studying"],
        explanation: "과거의 후회 → <code>should have + p.p</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그녀가 그렇게 말했을 리 없다.",
        prefix: ["She"],
        answer: ["cannot", "have", "said"],
        suffix: ["that", "."],
        distractors: ["cannot say", "must not say", "could not saying", "cannot have saying"],
        explanation: "과거의 강한 부정 확신 → <code>cannot have + p.p</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "너는 아침을 걸렀을지도 모른다.",
        prefix: ["You"],
        answer: ["may", "have", "skipped"],
        suffix: ["breakfast", "."],
        distractors: ["may skip", "must have skipped", "may skipping", "have may skipped"],
        explanation: "과거의 약한 추측 → <code>may/might have + p.p</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그는 우리를 도와줄 수도 있었다 (그런데 안 했다).",
        prefix: ["He"],
        answer: ["could", "have", "helped"],
        suffix: ["us", "."],
        distractors: ["could help", "would helped", "should have help", "could having helped"],
        explanation: "과거의 가능성 (실제로 안 한 일) → <code>could have + p.p</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "나는 그 편지를 보내지 말았어야 했다.",
        prefix: ["I"],
        answer: ["shouldn't", "have", "sent"],
        suffix: ["the", "letter", "."],
        distractors: ["shouldn't send", "didn't have to send", "shouldn't sending", "wasn't sent"],
        explanation: "과거의 후회(하지 말았어야) → <code>shouldn't have + p.p</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그녀는 이미 도착했을지도 모른다.",
        prefix: ["She"],
        answer: ["might", "have", "arrived"],
        suffix: ["already", "."],
        distractors: ["might arrive", "must have arrived", "might arriving", "may arrived"],
        explanation: "과거의 추측 → <code>might have + p.p</code> (may보다 약한 확신).",
      },
    ],
  },

  {
    id: "modal-idioms",
    title: "조동사 관용 — have to · ought to · used to 등",
    kind: "basic",
    short: "관용",
    group: "조동사",
    blurb: "must 옆 have to / should 옆 ought to / 과거 습관 used to",
    summary: [
      { t: "h", text: "주요 패턴" },
      {
        t: "table",
        head: ["표현", "의미", "예시"],
        rows: [
          ["<code>have to / has to / had to</code>", "~해야 한다 (외부 의무)", "I <b>have to</b> go now."],
          ["<code>ought to + 원형</code>", "~해야 한다 (도의적)", "You <b>ought to</b> apologize."],
          ["<code>had better + 원형</code>", "~하는 게 낫다 (강한 충고)", "You <b>had better</b> sleep now."],
          ["<code>would rather + 원형</code>", "차라리 ~하겠다", "I <b>would rather</b> stay home."],
          ["<code>used to + 원형</code>", "(과거에) ~하곤 했다 · ~였다 (지금은 아님)", "I <b>used to</b> play the piano."],
          ["<code>be used to + V-ing/명사</code>", "~에 익숙하다", "She <b>is used to</b> Korean food."],
          ["<code>be able to + 원형</code>", "~할 수 있다 (can과 유사, 시제·조동사 뒤 가능)", "He <b>will be able to</b> come."],
        ],
      },
      { t: "h", text: "혼동 포인트" },
      { t: "p", text: "• <b>used to + 원형</b> (~하곤 했다 · 과거의 습관/상태) vs <b>be used to + V-ing</b> (~에 익숙하다 · 지금 상태) — 뒤에 오는 형태가 다름!<br> • <b>must</b>는 과거형이 없어 과거엔 <b>had to</b>를 씀<br> • <b>had better</b> 부정: had better <b>not</b> + 원형" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 지금 가야 한다.",
        prefix: ["I"],
        answer: ["have to"],
        suffix: ["go", "now", "."],
        distractors: ["have", "must to", "should to", "had to"],
        explanation: "외부 의무 → <code>have to + 원형</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "너는 그 회의에 참석해야 한다.",
        prefix: ["You"],
        answer: ["ought to"],
        suffix: ["attend", "the", "meeting", "."],
        distractors: ["ought", "should to", "must to", "have"],
        explanation: "도의적 의무 → <code>ought to + 원형</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "너는 지금 자는 게 낫다.",
        prefix: ["You"],
        answer: ["had", "better"],
        suffix: ["sleep", "now", "."],
        distractors: ["have better", "would better", "had rather", "better had"],
        explanation: "강한 충고 → <code>had better + 원형</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "나는 차라리 집에 있고 싶다.",
        prefix: ["I"],
        answer: ["would", "rather"],
        suffix: ["stay", "home", "."],
        distractors: ["would better", "had rather", "should rather", "rather would"],
        explanation: "차라리 ~하겠다 → <code>would rather + 원형</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "나는 예전에 피아노를 치곤 했다 (지금은 아님).",
        prefix: ["I"],
        answer: ["used to"],
        suffix: ["play", "the", "piano", "."],
        distractors: ["was used to", "am used to", "use to", "used"],
        explanation: "과거 습관 → <code>used to + 원형</code>. \"지금은 아니다\"의 뉘앙스.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그녀는 한국 음식에 익숙하다.",
        prefix: ["She"],
        answer: ["is", "used", "to"],
        suffix: ["Korean", "food", "."],
        distractors: ["used to", "is using to", "was used to", "is use to"],
        explanation: "~에 익숙하다 → <code>be used to + 명사/V-ing</code>. \"과거 습관\"의 used to와 다름.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그는 내일 올 수 있을 것이다.",
        prefix: ["He"],
        answer: ["will", "be", "able", "to"],
        suffix: ["come", "tomorrow", "."],
        distractors: ["will can", "can be able to", "will be able", "is able to"],
        explanation: "미래의 능력 → <code>will be able to + 원형</code>. can은 미래조동사 will과 함께 못 씀.",
      },
    ],
  },

  {
    id: "adverb-clause",
    title: "부사절 접속사 심화 — 양보·조건·목적·시간",
    kind: "basic",
    short: "부사절 접속사",
    blurb: "although / unless / so that / in case / by the time",
    summary: [
      { t: "h", text: "양보 — \"~에도 불구하고\"" },
      {
        t: "table",
        head: ["접속사", "뉘앙스", "예시"],
        rows: [
          ["<code>although / though</code>", "사실을 인정하며 반대 진술", "<b>Although</b> he is rich, he is not happy."],
          ["<code>even though</code>", "강한 사실 인정", "<b>Even though</b> it rained, we went out."],
          ["<code>even if</code>", "가정에 가까움 — 설령 ~라 해도", "<b>Even if</b> it rains, we will go."],
        ],
      },
      { t: "h", text: "조건 — \"~라면 / ~하지 않는 한\"" },
      {
        t: "table",
        head: ["접속사", "의미"],
        rows: [
          ["<code>unless</code>", "~하지 않는 한 (= if ~ not)"],
          ["<code>as long as</code>", "~하는 한 (조건·시간 모두)"],
          ["<code>provided (that)</code>", "~라면 (격식)"],
          ["<code>in case</code>", "~할 경우에 대비하여"],
        ],
      },
      { t: "p", text: "주의: <b>unless는 이미 부정</b>이므로 뒤에 다시 not을 쓰지 않음.<br> (X) <s>Unless you don't hurry</s> → (O) <b>Unless you hurry</b>" },
      { t: "h", text: "목적 · 결과" },
      {
        t: "table",
        head: ["접속사", "의미", "예시"],
        rows: [
          ["<code>so that + 주어 + 조동사</code>", "~하기 위해 (목적)", "He studied <b>so that</b> he could pass."],
          ["<code>so ~ that</code>", "너무 ~해서 (결과)", "He was <b>so</b> tired <b>that</b> he slept."],
        ],
      },
      { t: "h", text: "시간 심화" },
      { t: "p", text: "<code>by the time</code>: ~할 즈음에 (완료의 기준점)<br> <code>as soon as</code>: ~하자마자 / <code>while</code>: ~하는 동안 / <code>since</code>: ~한 이래로 (완료와 함께)" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "비가 왔지만, 우리는 소풍을 갔다.",
        answer: ["Although"],
        suffix: ["it", "rained", ",", "we", "went", "on", "a", "picnic", "."],
        distractors: ["Because", "If", "Unless", "As"],
        explanation: "양보 — <code>Although + 사실</code>. 반대되는 사실 진술.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "서두르지 않으면, 늦을 것이다.",
        answer: ["Unless"],
        suffix: ["you", "hurry", ",", "you", "will", "be", "late", "."],
        distractors: ["If", "Although", "As", "Since"],
        explanation: "\"~하지 않는 한\" → <code>unless</code>. 부정이 이미 포함되어 뒤에 not 안 씀.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "네가 원하는 한 여기 있어도 된다.",
        prefix: ["You", "may", "stay", "here"],
        answer: ["as", "long", "as"],
        suffix: ["you", "want", "."],
        distractors: ["as soon as", "as far as", "even if", "in case"],
        explanation: "\"~하는 한\" → <code>as long as</code>. 조건의 뉘앙스.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그는 시험에 통과하기 위해 열심히 공부했다.",
        prefix: ["He", "studied", "hard"],
        answer: ["so", "that"],
        suffix: ["he", "could", "pass", "the", "exam", "."],
        distractors: ["so as", "in order", "such that", "so as that"],
        explanation: "목적 → <code>so that + 주어 + 조동사</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "비가 올 경우를 대비해 우산을 가져가라.",
        prefix: ["Take", "an", "umbrella"],
        answer: ["in", "case"],
        suffix: ["it", "rains", "."],
        distractors: ["in that", "in order", "so that", "as if"],
        explanation: "\"~할 경우에 대비하여\" → <code>in case</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "내가 도착했을 즈음에, 그는 이미 떠났다.",
        answer: ["By", "the", "time"],
        suffix: ["I", "arrived", ",", "he", "had", "already", "left", "."],
        distractors: ["Until", "As soon as", "When", "As long as"],
        explanation: "\"~할 즈음\" — 완료의 기준점 → <code>by the time</code>. 주절에 과거완료가 자주 옴.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "비록 그가 부자일지라도, 그는 행복하지 않다.",
        answer: ["Even", "though"],
        suffix: ["he", "is", "rich", ",", "he", "is", "not", "happy", "."],
        distractors: ["Even if", "Although not", "Because", "Since"],
        explanation: "\"비록 ~일지라도\" (사실 인정 강조) → <code>even though</code>. 사실을 강조.",
      },
    ],
  },

  {
    id: "connect-review",
    title: "접속사·전치사·조동사 통합 정리",
    kind: "review",
    short: "통합정리",
    blurb: "헷갈리는 짝꿍들 한 번에",
    summary: [
      { t: "h", text: "접속사 vs 전치사" },
      { t: "p", text: "둘 다 \"연결\" 역할이지만, 뒤에 오는 것이 다릅니다." },
      {
        t: "table",
        head: ["접속사", "전치사"],
        rows: [
          ["+ <b>주어 + 동사</b>", "+ <b>명사 / 명사구</b>"],
          ["because <u>it rained</u>", "because of <u>the rain</u>"],
          ["although <u>he was tired</u>", "despite <u>his tiredness</u>"],
        ],
      },
      { t: "h", text: "조동사 핵심 한 줄" },
      { t: "p", text: "1) 뒤에는 <b>항상 동사원형</b><br> 2) 주어와 상관없이 형태 변하지 않음 (he cans ✗)<br> 3) 두 개를 같이 못 씀 (will can ✗) → <code>will be able to</code>" },
      { t: "h", text: "in / on / at 빠른 점검" },
      { t: "p", text: "• 큰 시간/공간 → <b>in</b> (in 2025, in Seoul)<br> • 면/요일 → <b>on</b> (on the wall, on Monday)<br> • 점/시각 → <b>at</b> (at 7 o'clock, at the door)" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "비가 와서 우리는 집에 있었다.",
        prefix: ["We", "stayed", "home"],
        answer: ["because"],
        suffix: ["it", "rained", "."],
        distractors: ["because of", "so", "but", "although"],
        explanation: "뒤에 <b>주어+동사</b>(it rained) → 접속사 <code>because</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "비 때문에 우리는 집에 있었다.",
        prefix: ["We", "stayed", "home"],
        answer: ["because of"],
        suffix: ["the", "rain", "."],
        distractors: ["because", "so that", "although", "despite of"],
        explanation: "뒤에 <b>명사</b>(the rain) → 전치사구 <code>because of</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그는 한국어를 할 수 있다.",
        prefix: ["He"],
        answer: ["can", "speak"],
        suffix: ["Korean", "."],
        distractors: ["cans speak", "can speaks", "is speak", "could speaks"],
        explanation: "조동사 뒤는 원형 — 주어가 he여도 형태 변하지 않음.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그는 8시에 집을 떠난다.",
        prefix: ["He", "leaves", "home"],
        answer: ["at"],
        suffix: ["8", "o'clock", "."],
        distractors: ["in", "on", "to", "by"],
        explanation: "시각 → <code>at</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "비가 오면 우리는 갈 수 없다.",
        answer: ["If"],
        suffix: ["it", "rains", ",", "we", "can't", "go", "."],
        distractors: ["When", "Because", "Although", "So"],
        explanation: "조건 → <code>If</code>.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "너는 그곳에 갈 필요가 없다.",
        prefix: ["You"],
        answer: ["don't", "have", "to", "go"],
        suffix: ["there", "."],
        distractors: ["mustn't go", "haven't go", "don't has to go", "have to don't go"],
        explanation: "<code>don't have to + 원형</code> — 불필요.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그녀는 친구와 함께 공부했다.",
        prefix: ["She", "studied"],
        answer: ["with"],
        suffix: ["her", "friend", "."],
        distractors: ["by", "to", "for", "in"],
        explanation: "동반 → <code>with</code>.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "비록 피곤했지만 그는 일했다.",
        answer: ["Although"],
        suffix: ["he", "was", "tired", ",", "he", "worked", "."],
        distractors: ["Despite", "Because", "If", "So"],
        explanation: "뒤에 <b>주어+동사</b> → 접속사 <code>Although</code>.",
      },
      {
        id: "c1",
        type: "choice",
        ko: "나는 8시에 일어난다.",
        choices: ["at", "on"],
        correct: 0,
        sentence: ["I get up", null, "8 o'clock", "."],
        explanation: "구체적인 시각 앞에는 <code>at</code>.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "그는 수영을 할 수 있다.",
        choices: ["can", "can to"],
        correct: 0,
        sentence: ["He", null, "swim", "."],
        explanation: "조동사 뒤에는 to 없이 동사원형.",
      },
      {
        id: "e1",
        type: "error",
        ko: "나는 5월 5일에 태어났다.",
        tokens: ["I", "was", "born", "in", "May", "5th", "."],
        wrongIndex: 3,
        fix: "on",
        explanation: "날짜 앞에는 <code>on</code>. 달 이름만 있을 때만 <code>in May</code>.",
      },
      {
        id: "e2",
        type: "error",
        ko: "그녀는 노래를 아주 잘한다.",
        tokens: ["She", "can", "sings", "very", "well", "."],
        wrongIndex: 2,
        fix: "sing",
        explanation: "조동사 <code>can</code> 뒤에는 동사원형.",
      },
    ],
  },
];
