// part7Verbal — 콘텐츠 파일. 형식은 src/content/schema.js 참고.

export const part7Verbal = [
  {
    id: "to-infinitive",
    title: "to부정사 — to + 동사원형",
    kind: "basic",
    short: "to부정사",
    blurb: "동사를 명사·형용사·부사로 변신시키는 기본기",
    summary: [
      { t: "h", text: "형태" },
      { t: "p", text: "<b>to + 동사원형</b>. 동사이지만 문장에서 명사·형용사·부사 역할을 합니다." },
      { t: "h", text: "3가지 용법" },
      {
        t: "table",
        head: ["용법", "의미", "예시"],
        rows: [
          ["명사적", "~하는 것", "<b>To study</b> English is fun. / I want <b>to go</b>."],
          ["형용사적", "~할, ~하는", "I have a book <b>to read</b>."],
          ["부사적", "~하기 위해 / ~해서", "He came <b>to see</b> you. / I'm happy <b>to hear</b> it."],
        ],
      },
      { t: "h", text: "to부정사를 목적어로 받는 동사" },
      { t: "p", text: "<code>want, hope, plan, decide, promise, learn, expect, agree</code> 등" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 영어를 배우고 싶다.",
        prefix: ["I", "want"],
        answer: ["to learn"],
        suffix: ["English", "."],
        distractors: ["learning", "learn", "to learning", "learned"],
        explanation: "<b>want</b>는 to부정사를 목적어로 받는 동사 — <code>want to + 원형</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그녀의 꿈은 의사가 되는 것이다.",
        prefix: ["Her", "dream", "is"],
        answer: ["to become"],
        suffix: ["a", "doctor", "."],
        distractors: ["becoming", "become", "to becoming", "became"],
        explanation: "주어와 같은 \"~인 것\" 의미 — 명사적 용법(보어).",
      },
      {
        id: "q3",
        type: "blank",
        ko: "나는 읽을 책이 있다.",
        prefix: ["I", "have", "a", "book"],
        answer: ["to read"],
        suffix: ["."],
        distractors: ["reading", "for read", "read", "for reading"],
        explanation: "앞 명사 <code>book</code>을 꾸미는 형용사적 용법 — \"읽을\".",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그는 너를 만나기 위해 왔다.",
        prefix: ["He", "came"],
        answer: ["to see"],
        suffix: ["you", "."],
        distractors: ["seeing", "for see", "see", "for seeing"],
        explanation: "목적(~하기 위해) — 부사적 용법.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "영어를 공부하는 것은 재미있다.",
        answer: ["To study"],
        suffix: ["English", "is", "fun", "."],
        distractors: ["Studying", "Study", "For study", "Studies"],
        explanation: "주어 자리 → 명사적 용법. (참고로 동명사 Studying도 가능하지만, 여기선 to부정사 형태가 정답).",
      },
      {
        id: "q6",
        type: "blank",
        ko: "나는 마실 무언가가 필요하다.",
        prefix: ["I", "need", "something"],
        answer: ["to drink"],
        suffix: ["."],
        distractors: ["drinking", "drink", "for drink", "for drinking"],
        explanation: "<code>-thing</code>을 꾸미는 형용사적 용법.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그녀는 그 소식을 듣고 행복해했다.",
        prefix: ["She", "was", "happy"],
        answer: ["to hear"],
        suffix: ["the", "news", "."],
        distractors: ["hearing", "to hearing", "hear", "heard"],
        explanation: "감정의 원인(~해서) — 부사적 용법.",
      },
    ],
  },

  {
    id: "gerund",
    title: "동명사 — V-ing의 명사 역할",
    kind: "basic",
    short: "동명사",
    blurb: "동사ing가 명사 자리에 들어가는 경우",
    summary: [
      { t: "h", text: "형태" },
      { t: "p", text: "<b>동사 + ing</b>. 형태는 현재분사와 같지만, <b>명사 역할</b>을 할 때 동명사라고 부릅니다." },
      { t: "h", text: "4가지 자리" },
      {
        t: "ul",
        items: [
          "주어: <b>Reading</b> books is fun.",
          "목적어: I enjoy <b>reading</b> books.",
          "보어: My hobby is <b>reading</b>.",
          "전치사의 목적어: She is good at <b>singing</b>.",
        ],
      },
      { t: "h", text: "동명사를 목적어로 받는 동사" },
      { t: "p", text: "<code>enjoy, finish, mind, give up, avoid, keep, stop, practice, suggest</code>" },
      { t: "h", text: "주의 — to부정사 vs 동명사" },
      { t: "p", text: "• <code>want, hope, plan, decide</code> + to부정사<br> • <code>enjoy, finish, mind</code> + 동명사<br> • <code>like, love, hate, begin, start</code>: 둘 다 가능 (의미 비슷)" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "영어 공부하는 것은 어렵다.",
        answer: ["Studying"],
        suffix: ["English", "is", "difficult", "."],
        distractors: ["To studying", "Study", "Studied", "Studies"],
        explanation: "주어 자리 동명사.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "나는 책 읽는 것을 즐긴다.",
        prefix: ["I", "enjoy"],
        answer: ["reading"],
        suffix: ["books", "."],
        distractors: ["to read", "read", "to reading", "reads"],
        explanation: "<b>enjoy</b>는 동명사만 목적어로 받음.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그녀는 노래를 잘 부른다.",
        prefix: ["She", "is", "good", "at"],
        answer: ["singing"],
        suffix: ["."],
        distractors: ["to sing", "sing", "sang", "sings"],
        explanation: "전치사 <b>at</b> 뒤에는 동명사 (전치사의 목적어).",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그의 취미는 사진 찍기다.",
        prefix: ["His", "hobby", "is"],
        answer: ["taking"],
        suffix: ["pictures", "."],
        distractors: ["to take", "take", "took", "takes"],
        explanation: "보어 자리의 동명사 — 취미·습관을 말할 때 자연스러움.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그녀는 새로운 사람들 만나는 것을 좋아한다.",
        prefix: ["She", "likes"],
        answer: ["meeting"],
        suffix: ["new", "people", "."],
        distractors: ["to meeting", "meet", "met", "meets"],
        explanation: "<b>like</b>는 동명사/to부정사 모두 가능. 여기선 동명사 형태가 정답.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "운동하는 것은 건강에 좋다.",
        answer: ["Exercising"],
        suffix: ["is", "good", "for", "your", "health", "."],
        distractors: ["To exercising", "Exercise", "Exercised", "Exercises"],
        explanation: "주어 자리의 동명사.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그들은 컴퓨터 게임을 멈추지 않는다.",
        prefix: ["They", "never", "stop"],
        answer: ["playing"],
        suffix: ["computer", "games", "."],
        distractors: ["to play", "play", "played", "plays"],
        explanation: "<b>stop + 동명사</b>: ~하는 것을 멈추다. (참고: <code>stop to V</code>는 \"~하기 위해 멈추다\"로 의미가 다름)",
      },
    ],
  },

  {
    id: "participle",
    title: "분사 — 동사가 형용사 역할",
    kind: "basic",
    short: "분사",
    blurb: "현재분사(~ing)와 과거분사(p.p)로 명사 꾸미기",
    summary: [
      { t: "h", text: "두 가지 분사" },
      {
        t: "table",
        head: ["분사", "형태", "의미", "예시"],
        rows: [
          ["현재분사", "V-ing", "능동·진행 (~하는, ~하고 있는)", "a <b>running</b> boy"],
          ["과거분사", "p.p", "수동·완료 (~된, ~당한)", "a <b>broken</b> window"],
        ],
      },
      { t: "h", text: "명사를 꾸미는 두 위치" },
      { t: "p", text: "• 단어 하나일 때 → 명사 <b>앞</b>: <code>a sleeping baby</code><br> • 구(2단어 이상)일 때 → 명사 <b>뒤</b>: <code>the boy <b>standing over there</b></code> / <code>the book <b>written by him</b></code>" },
      { t: "h", text: "혼동 포인트 — 감정 형용사" },
      { t: "p", text: "주어가 <b>감정을 일으키는 쪽</b>이면 -ing, <b>느끼는 쪽</b>이면 -ed.<br> The movie is <b>interesting</b>. (영화가 흥미를 일으킴)<br> I am <b>interested</b> in the movie. (나는 흥미를 느낌)" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "우는 아기 (한 명을 가리키며)",
        prefix: ["a"],
        answer: ["crying"],
        suffix: ["baby"],
        distractors: ["cried", "cry", "to cry", "cries"],
        explanation: "능동(아기가 운다) → 현재분사 <code>crying</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "깨진 창문",
        prefix: ["a"],
        answer: ["broken"],
        suffix: ["window"],
        distractors: ["breaking", "break", "broke", "breaks"],
        explanation: "수동(창문이 깨졌다) → 과거분사 <code>broken</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "영어를 가르치는 그 선생님",
        prefix: ["the", "teacher"],
        answer: ["teaching"],
        suffix: ["English"],
        distractors: ["taught", "teach", "to teach", "teaches"],
        explanation: "구가 명사를 뒤에서 수식. 선생님이 능동적으로 가르침 → 현재분사.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "한국에서 만들어진 그 차",
        prefix: ["the", "car"],
        answer: ["made"],
        suffix: ["in", "Korea"],
        distractors: ["making", "make", "to make", "makes"],
        explanation: "차가 만들어진다(수동) → 과거분사.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "그는 자고 있는 아이를 보았다.",
        prefix: ["He", "saw", "the"],
        answer: ["sleeping"],
        suffix: ["child", "."],
        distractors: ["slept", "sleep", "to sleep", "sleeps"],
        explanation: "아이가 자고 있는 중(능동·진행) → 현재분사.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "그 책은 도난당했다.",
        prefix: ["The", "book", "was"],
        answer: ["stolen"],
        suffix: ["."],
        distractors: ["stealing", "steal", "stole", "steals"],
        explanation: "수동태(be + p.p)이자 분사의 활용. <code>steal</code>의 p.p는 <code>stolen</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그것은 흥미로운 영화다.",
        prefix: ["It", "is", "an"],
        answer: ["interesting"],
        suffix: ["movie", "."],
        distractors: ["interested", "interest", "to interest", "interests"],
        explanation: "영화가 흥미를 일으킴(능동) → -ing.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "나는 그 결과에 흥미를 느꼈다.",
        prefix: ["I", "was"],
        answer: ["interested"],
        suffix: ["in", "the", "result", "."],
        distractors: ["interesting", "interest", "to interest", "interests"],
        explanation: "내가 흥미를 느낌(수동) → -ed. <code>be interested in</code>으로 외움.",
      },
    ],
  },

  {
    id: "participial-construction",
    title: "분사구문 — 부사절을 분사로 압축",
    kind: "basic",
    short: "분사구문",
    blurb: "When/Because/If ~를 V-ing 하나로 줄이는 고급 표현",
    summary: [
      { t: "h", text: "분사구문이란?" },
      { t: "p", text: "<b>부사절</b>(when·because·if·though 등으로 시작하는 절)을 <b>분사(V-ing 또는 p.p) 하나로 압축</b>한 구문. 문장을 간결하게 만드는 고급 표현입니다." },
      { t: "h", text: "만드는 3단계" },
      {
        t: "table",
        head: ["원래 문장", { text: "When she saw me, she smiled.", span: 3 }],
        rows: [
          ["① 접속사 삭제", { text: "<s>When</s> she saw me, she smiled.", span: 3 }],
          ["② 주절과 같은 주어 삭제", { text: "<s>she</s> saw me, she smiled.", span: 3 }],
          ["③ 동사를 분사(V-ing)로", { text: "<b>Seeing me, she smiled.</b>", span: 3 }],
        ],
      },
      { t: "h", text: "네 가지 형태" },
      {
        t: "table",
        head: ["형태", "의미", "예시"],
        rows: [
          ["<code>V-ing</code>", "단순 — 같은 시제", "<b>Seeing</b> me, she smiled."],
          ["<code>Having + p.p</code>", "완료 — 주절보다 먼저 일어남", "<b>Having finished</b> homework, he went out."],
          ["<code>Being + p.p</code> 또는 <code>p.p</code>", "수동 (Being 생략 가능)", "<b>Made</b> in Korea, the car is popular."],
          ["<code>Not + V-ing</code>", "부정 — not이 분사 앞", "<b>Not knowing</b> what to do, I stayed quiet."],
        ],
      },
      { t: "h", text: "의미의 다양성" },
      { t: "p", text: "같은 분사구문이 문맥에 따라 <b>시간·이유·조건·양보·부대상황</b> 여러 뜻을 나타냅니다.<br> <code>Living in Seoul, I can meet many friends.</code> — 서울에 살기 때문에(이유) / 살아서(조건)" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나를 보자, 그녀는 웃었다.",
        answer: ["Seeing"],
        suffix: ["me", ",", "she", "smiled", "."],
        distractors: ["Saw", "Seen", "To see", "Being seen"],
        explanation: "When she saw me의 압축 — 능동 → <code>V-ing</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "피곤해서 나는 잠자리에 들었다.",
        answer: ["Being", "tired"],
        suffix: [",", "I", "went", "to", "bed", "."],
        distractors: ["Tiring", "Tired being", "To tired", "Was tired"],
        explanation: "Because I was tired의 압축. 상태·수동 → <code>Being + 형용사/p.p</code>. (Being은 생략 가능)",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그의 이름을 듣고, 나는 놀랐다.",
        answer: ["Hearing"],
        suffix: ["his", "name", ",", "I", "was", "surprised", "."],
        distractors: ["Heard", "To hear", "Being heard", "Had heard"],
        explanation: "When I heard의 압축 — 단순 V-ing.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "숙제를 다 끝내고 나서, 그는 나갔다.",
        answer: ["Having finished"],
        suffix: ["his", "homework", ",", "he", "went", "out", "."],
        distractors: ["Finishing", "Finished", "Being finished", "Having finish"],
        explanation: "주절보다 먼저 일어난 일 → 완료 분사구문 <code>Having + p.p</code>.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "한국에서 만들어져서, 이 차는 인기가 많다.",
        answer: ["Made"],
        suffix: ["in", "Korea", ",", "this", "car", "is", "popular", "."],
        distractors: ["Making", "Being make", "Having made", "To make"],
        explanation: "수동 분사구문에서 Being이 생략된 형태 — <code>p.p</code>만 남음.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "무엇을 해야 할지 몰라서, 나는 조용히 있었다.",
        answer: ["Not", "knowing"],
        suffix: ["what", "to", "do", ",", "I", "stayed", "quiet", "."],
        distractors: ["Don't know", "Knowing not", "Not know", "Being not known"],
        explanation: "부정 분사구문 — <code>not</code>이 분사 <b>앞</b>에 옴.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "열심히 공부해서, 그녀는 시험에 합격했다.",
        answer: ["Studying"],
        suffix: ["hard", ",", "she", "passed", "the", "exam", "."],
        distractors: ["Studied", "To study", "Having study", "Being studied"],
        explanation: "Because she studied hard의 압축.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "이전에 그 영화를 본 적이 있어서, 나는 다시 보지 않았다.",
        answer: ["Having seen"],
        suffix: ["the", "movie", "before", ",", "I", "didn't", "watch", "it", "again", "."],
        distractors: ["Seeing", "Seen", "Being seen", "Having saw"],
        explanation: "주절(과거)보다 더 이전의 일 → 완료 분사구문 <code>Having + p.p</code>.",
      },
    ],
  },

  {
    id: "verbal-advanced",
    title: "준동사 심화 — 의미상 주어·완료형·가주어/가목적어",
    kind: "basic",
    short: "심화",
    blurb: "for me to / of you to / to have p.p / It ~ to부정사",
    summary: [
      { t: "h", text: "의미상 주어 — 준동사의 실제 주체" },
      { t: "p", text: "준동사(to부정사·동명사) 앞에 <b>그 동작의 주체</b>를 명시할 때 씁니다. 문장 주어와 다를 때 필요." },
      {
        t: "table",
        head: ["준동사", "의미상 주어 형태", "예시"],
        rows: [
          ["to부정사 (일반)", "<code>for + 목적격</code>", "It is easy <b>for me</b> to read."],
          ["to부정사 (사람 성질 형용사)", "<code>of + 목적격</code>", "It is kind <b>of you</b> to help."],
          ["동명사", "소유격 또는 목적격", "I don't like <b>his</b> smoking."],
        ],
      },
      { t: "p", text: "of를 쓰는 형용사: <code>kind, nice, foolish, careless, wise, rude, generous, silly</code> 등 <b>사람의 성질·태도</b>를 나타내는 것들." },
      { t: "h", text: "완료 부정사·완료 동명사 — 시제 밀어내기" },
      { t: "p", text: "준동사가 나타내는 시점이 <b>주절 시제보다 이전</b>일 때 완료형을 씁니다." },
      {
        t: "table",
        head: ["형태", "공식", "예시"],
        rows: [
          ["완료 부정사", "<code>to have + p.p</code>", "He seems <b>to have been</b> sick. (아팠던 것 같다)"],
          ["완료 동명사", "<code>having + p.p</code>", "She is proud of <b>having won</b>. (이겼던 걸 자랑스러워한다)"],
        ],
      },
      { t: "h", text: "가주어 · 가목적어 It" },
      { t: "p", text: "영어는 주어·목적어 자리가 길어지는 것을 싫어합니다. to부정사구/that절이 오면 <b>It</b>을 앞에 놓고 실제 내용은 뒤로 보냅니다." },
      {
        t: "ul",
        items: [
          "가주어: <b>It</b> is important <b>to study English</b>. (= To study English is important.)",
          "가주어: <b>It</b> is true <b>that he is honest</b>.",
          "가목적어: I found <b>it</b> hard <b>to understand him</b>. (make/find/think 뒤 자주 나옴)",
        ],
      },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "네가 그 책을 읽는 것은 쉽다.",
        prefix: ["It", "is", "easy"],
        answer: ["for", "you"],
        suffix: ["to", "read", "the", "book", "."],
        distractors: ["of you", "for your", "of yours", "to you"],
        explanation: "일반적 to부정사 의미상 주어 → <code>for + 목적격</code>.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "네가 그것을 하다니 친절하다.",
        prefix: ["It", "is", "kind"],
        answer: ["of", "you"],
        suffix: ["to", "do", "that", "."],
        distractors: ["for you", "of your", "for your", "to you"],
        explanation: "사람의 성질(kind) 형용사 뒤 → <code>of + 목적격</code>.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "그는 아팠던 것 같다.",
        prefix: ["He", "seems"],
        answer: ["to", "have", "been"],
        suffix: ["sick", "."],
        distractors: ["to be", "having been", "to being", "to has been"],
        explanation: "주절(seems: 현재)보다 이전 시점 → 완료 부정사 <code>to have + p.p</code>.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "나는 그가 담배 피우는 것이 싫다.",
        prefix: ["I", "don't", "like"],
        answer: ["his"],
        suffix: ["smoking", "."],
        distractors: ["him is", "of him", "for him", "he"],
        explanation: "동명사의 의미상 주어 → 소유격(격식) 또는 목적격. 시험에선 소유격 <code>his</code>가 정석.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "영어 공부하는 것이 중요하다.",
        answer: ["It", "is"],
        suffix: ["important", "to", "study", "English", "."],
        distractors: ["This is", "That is", "There is", "It's"],
        explanation: "가주어 <code>It</code> — to부정사가 실제 주어.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "나는 그를 이해하는 것이 어렵다고 생각했다.",
        prefix: ["I", "found"],
        answer: ["it"],
        suffix: ["hard", "to", "understand", "him", "."],
        distractors: ["that", "this", "him", "so"],
        explanation: "가목적어 <code>it</code> — <code>find/make/think + it + 형용사 + to부정사</code>.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "그녀는 부자였던 것 같다.",
        prefix: ["She", "seems"],
        answer: ["to", "have", "been"],
        suffix: ["rich", "."],
        distractors: ["to be", "having been", "to was", "to being"],
        explanation: "주절보다 이전(과거) → 완료 부정사.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "네가 그 사실을 알다니 현명하다.",
        prefix: ["It", "is", "wise"],
        answer: ["of", "you"],
        suffix: ["to", "know", "the", "fact", "."],
        distractors: ["for you", "of your", "for your", "to you"],
        explanation: "wise는 사람의 성질 형용사 → <code>of + 목적격</code>.",
      },
    ],
  },

  {
    id: "verbal-review",
    title: "준동사 통합 정리",
    kind: "review",
    short: "통합정리",
    blurb: "to부정사 · 동명사 · 분사 종합",
    summary: [
      { t: "h", text: "준동사 한눈에" },
      {
        t: "table",
        head: ["종류", "형태", "역할"],
        rows: [
          ["to부정사", "to + 원형", "명사·형용사·부사"],
          ["동명사", "V-ing", "명사"],
          ["분사", "V-ing / p.p", "형용사"],
        ],
      },
      { t: "h", text: "핵심 선택 가이드" },
      { t: "p", text: "• <b>want / plan / decide</b> 뒤 → to부정사<br> • <b>enjoy / finish / mind</b> 뒤 → 동명사<br> • <b>전치사</b> 뒤 → 동명사<br> • <b>명사 수식</b> 능동 → V-ing / 수동 → p.p" },
    ],
    questions: [
      {
        id: "q1",
        type: "blank",
        ko: "나는 새 직업을 찾기로 결심했다.",
        prefix: ["I", "decided"],
        answer: ["to look"],
        suffix: ["for", "a", "new", "job", "."],
        distractors: ["looking", "look", "to looking", "looked"],
        explanation: "<b>decide</b> + to부정사.",
      },
      {
        id: "q2",
        type: "blank",
        ko: "그는 담배 피우는 것을 포기했다.",
        prefix: ["He", "gave", "up"],
        answer: ["smoking"],
        suffix: ["."],
        distractors: ["to smoke", "smoke", "smoked", "to smoking"],
        explanation: "<b>give up</b> + 동명사.",
      },
      {
        id: "q3",
        type: "blank",
        ko: "내가 그를 만났을 때 그는 친구들과 이야기하고 있었다.",
        prefix: ["When", "I", "met", "him", ",", "he", "was"],
        answer: ["talking"],
        suffix: ["with", "friends", "."],
        distractors: ["talked", "to talk", "talks", "talk"],
        explanation: "과거진행 — be + 현재분사.",
      },
      {
        id: "q4",
        type: "blank",
        ko: "그녀는 영어 말하기를 잘한다.",
        prefix: ["She", "is", "good", "at"],
        answer: ["speaking"],
        suffix: ["English", "."],
        distractors: ["to speak", "speak", "spoke", "speaks"],
        explanation: "전치사 at 뒤 → 동명사.",
      },
      {
        id: "q5",
        type: "blank",
        ko: "여기 영어로 쓰인 편지가 있다.",
        prefix: ["Here", "is", "a", "letter"],
        answer: ["written"],
        suffix: ["in", "English", "."],
        distractors: ["writing", "write", "wrote", "to write"],
        explanation: "편지가 쓰여진(수동) → 과거분사. 구는 명사 뒤에서 수식.",
      },
      {
        id: "q6",
        type: "blank",
        ko: "나는 너를 다시 만나서 기쁘다.",
        prefix: ["I'm", "glad"],
        answer: ["to see"],
        suffix: ["you", "again", "."],
        distractors: ["seeing", "see", "to seeing", "saw"],
        explanation: "감정의 원인 — to부정사의 부사적 용법.",
      },
      {
        id: "q7",
        type: "blank",
        ko: "이 노래는 신난다.",
        prefix: ["This", "song", "is"],
        answer: ["exciting"],
        suffix: ["."],
        distractors: ["excited", "excite", "to excite", "excites"],
        explanation: "노래가 흥분을 일으킴 → -ing.",
      },
      {
        id: "q8",
        type: "blank",
        ko: "그녀는 손을 흔드는 것을 멈추지 않았다.",
        prefix: ["She", "didn't", "stop"],
        answer: ["waving"],
        suffix: ["her", "hand", "."],
        distractors: ["to wave", "wave", "waved", "waves"],
        explanation: "<b>stop + 동명사</b>: ~하는 것을 멈추다.",
      },
      {
        id: "c1",
        type: "choice",
        ko: "나는 영어를 배우기로 결심했다.",
        choices: ["to learn", "learning"],
        correct: 0,
        sentence: ["I decided", null, "English", "."],
        explanation: "<b>decide</b>는 to부정사를 목적어로 받는다.",
      },
      {
        id: "c2",
        type: "choice",
        ko: "그는 담배 피우는 것을 그만두었다.",
        choices: ["smoking", "to smoke"],
        correct: 0,
        sentence: ["He stopped", null, "."],
        explanation: "<code>stop + V-ing</code>는 '하던 것을 그만두다'. <code>stop to V</code>는 '하려고 멈추다'.",
      },
      {
        id: "e1",
        type: "error",
        ko: "그는 집에 가고 싶어 한다.",
        tokens: ["He", "wants", "going", "home", "."],
        wrongIndex: 2,
        fix: "to go",
        explanation: "<b>want</b>는 to부정사를 목적어로 받는다.",
      },
      {
        id: "e2",
        type: "error",
        ko: "숙제를 다 끝내고 나서, 그는 나갔다.",
        tokens: ["Finished", "his", "homework", ",", "he", "went", "out", "."],
        wrongIndex: 0,
        fix: "Having finished",
        explanation: "주절보다 앞선 일을 나타내는 분사구문 → <code>Having + p.p</code>.",
      },
    ],
  },
];
